### ISSUE TITLE
Provide hosted builds

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/enigma.js#1]
It would have been nice to host the latest build of the master branch on a CDN or through some other means so we can easily use the library with services such as jsfiddle or jsbin.

This would allow us to create a larger eco-system of examples and snippets to drive adoption.

**Comment by stoffeastrom** [comment]
I guess it could be accessed through [CirclecCI](https://github.com/qlik-oss/enigma.js/blob/master/circle.yml#L7) but it might not be public.

**Comment by mindspank** [comment]
https://rawgit.com/ is a nice service that might be worth looking into and heavily used in other open source projects. I mean I could just fork it for myself, build and commit the output but would have been nice with something simple for everyone to use.

**Comment by peol** [comment]
This might be something we'd set up long-term, but we want to avoid having built files (`dist/`) in the repository. Circle CI is public, but doesn't have a simple API to refer to the latest build artifact.

@mindspank For you purposes, you should probably not reference bleeding-edge versions anyway, there are however services like `unpkg` that lets you consume files from npm modules.

Here's `enigma.js@1.0.0`: https://unpkg.com/enigma.js@1.0.0/dist/enigma.min.js

**Comment by mindspank** [comment]
@peol Perfect! I did not know about unpkg, thanks! That should be sufficient enough for what I'm looking to do, closing the issue.
