### ISSUE TITLE
Not clear how to authenticate

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#10]
Hi,

I see no documentation about how to authenticate? an example for certificates and header would be nice.

thanks

**Comment by QHose** [comment]
https://github.com/qlik-oss/enigma.js/blob/master/docs/authentication.md

**Comment by QHose** [comment]
Ok, there is some documentation. But it it still not clear how to use certificates. E.g. with QSocks we had to setup the connection like this.

```
export var certicate_communication_options = {
        rejectUnauthorized: false,
        hostname: _senseConfig.SenseServerInternalLanIP,
        headers: {
            'x-qlik-xrfkey': _senseConfig.xrfkey,
            'X-Qlik-User': Meteor.settings.private.engineHeaders,
            'Content-Type': 'application/json'
        },
        key: _certs.key,
        cert: _certs.cert
    };
```

```
 return await qsocks.Connect(engineConfig)
        .then(function(global) {
            // console.log('connected to Qsocks');
            _global = global;
            return global.openDoc(appId, '', '', '', true) //global.openDoc(appId), this code opens the app without data, that is faster!
        })
        .then(function(doc) {
            // console.log('** getAppsViaEngine, QSocks opened and now tries to set the script for appId: ', appId);
            return doc.getScript()
                .then(function(script) {
                    // console.log('get Script success, ', script);

                    var call = {};
```

**Comment by mindspank** [comment]
https://github.com/qlik-oss/enigma.js/blob/master/docs/qix/configuration.md#example-using-nodejs

**Comment by QHose** [comment]
Thanks, Maybe we can make a good table of contents in the landing page, that links to these examples

**Comment by peol** [comment]
Thanks @QHose and @mindspank!

We are planning on doing some work regarding the documentation during the next coming weeks and we'll try to create a better ToC during that work. I'm closing this issue for now since the information does exist.

**Comment by QHose** [comment]
link is dead now
