### ISSUE TITLE
Performance tests on critical paths

### ISSUE THREAD

**Issue by peol** [qlik-oss/enigma.js#111]
To make sure we always work towards a faster enigma.js implementation, we should have a set of benchmarks we can run as part of our CI.

Some things I had in mind initially:

* Serializing responses in parallell (e.g. run `getLayout()` a lot of times)
* With and without delta protocol
* Memory consumption per request/response
* Memory consumption over time
* Event triggering and blocking handlers
* Bandwidth

And once we have a baseline I'd like us to see if we can improve in these areas, specifically serialization is one area I'm sure is causing a bit of a performance bottleneck today (JSON.stringify/parse to clone an object, we may want to check for other approaches like: https://jsperf.com/deep-copy-vs-json-stringify-json-parse/5), the JSON patch implementation can probably be improved as well.

**Comment by stoffeastrom** [comment]
I was wondering about the JSON.stringify/parse and I guess you mean [this](https://github.com/qlik-oss/enigma.js/blob/master/src/intercept.js#L122)? Doesn't that go against the JSON Patch spec?

**Comment by peol** [comment]
@stoffeastrom Indeed. No, the JSONPatch spec is about patching one object into matching another, not about object references per se. The code you linked to was added to avoid patching object references during parallel requests when the intercept chain is running which caused e.g. `GetObject` to return the same API in `processObjectApiInterceptor` due to another response patching the object reference.

**Comment by stoffeastrom** [comment]
@peol Thanks for explanation. Just another quick question :). Was it returning an incorrect API meaning a completely different API or an invalid API?

**Comment by peol** [comment]
@stoffeastrom No worries :) Since the second `GetObject` would get a patch for another `qHandle` and `qType`, everything _seemed_ to work, but the first `GetObject` would actually return an API based on the second `GetObject`'s result (wrong handle and potentially wrong genericType).

**Comment by stoffeastrom** [comment]
@peol Oh I see. Now I think I understand the problem :). The [`deltaCache`](https://github.com/qlik-oss/enigma.js/blob/master/src/intercept.js#L119) is per `handle` and `method` and `key` and since the `GetObject`'s is on the `Doc`that is troublesome. Just thinking out loud, it might be worth looking into how the `deltaCache` is handled for `Doc`'s `GetObject`'s (and remove the stringify/parse) for this issue e.g measure the performance. E.g anything that actually returns an api should have a separate `deltaCache`.

**Comment by peol** [comment]
@stoffeastrom Yeah, exactly. But basically any QIX method can cause these issues (depending on the mixins and interceptors used to augment the API) so it's tricky :) But we should definitely start with a performance baseline, even if work like this could be done in parallell!

**Comment by peol** [comment]
Another concern was immutability. If you do `getLayout()`, you may assume that whatever you get back will never change, which is not true (obviously) when it's patched object references.

But another way of approaching it is to make the interceptor queue synchronous (all build-in interceptors could be sync), and allow async interceptors but with the disclaimer that it may affect performance (causing us to clone the object).

**Comment by stoffeastrom** [comment]
True, needs some good thinking to flesh out all possibilities.

**Comment by peol** [comment]
We may revisit this in the future in another issue, closing this for now.
