### ISSUE TITLE
Misleading config documentation without route?

### ISSUE THREAD

**Issue by skokenes** [qlik-oss/enigma.js#140]
In the docs for configuration https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#configuration, it shows the following WebSocket url:

`url: 'ws://localhost:4848/app',`

Is this a valid URL? When I try that against a June 2017 Sense server, I get an error. However, if I use the `engineData` route at the end like so:

`url: 'ws://localhost:4848/app/engineData',`

it works. Is there any documentation anywhere about what routes are, what is valid, how they should be used? I find this a point of confusion for new users

**Comment by skokenes** [comment]
Update: testing with a June 2017 server, I observe the following behavior:

`url: 'ws://host/app'` -> WebSocket connection errors with 301 code

`url: 'ws://host/app/'` -> WebSocket connects without issue

The documentation linked above and the help.qlik.com docs state that you can create a session with a URL in the format: `port://host/app`. Either this is incorrect and it requires a `/` at the end, or my server could be configured incorrectly?

**Comment by peol** [comment]
Hi @skokenes. You are right, the needs to be an ending slash to that route. The `engineData` part is for the Sense Proxy to validate the session and AFAIK not used outside of Sense Enterprise. For concistency's sake it makes sense to have it so I'll keep this issue open until we have updated the documentation.

**Comment by skokenes** [comment]
@peol thanks. Is there a place where I can submit this feedback for the Qlik Help docs as well, or can you pass along? For example, at http://help.qlik.com/en-US/sense-developer/June2017/Subsystems/EngineAPI/Content/GettingStarted/connecting-to-engine-api.htm it says

> Qlik Sense Desktop
> 
> After you launch Qlik Sense Desktop and log in, you can connect to the Qlik Engine API using the following URI:
> 
> ws://localhost:4848/app/
> 
> For example, using JavaScript in a browser, make the following call:
> 
> var ws = new WebSocket(**"ws://localhost:4848/app"**);

**Comment by peol** [comment]
@skokenes I'll send it to our docs team, thanks!
