### ISSUE TITLE
Multiple apps in parallel using Sense

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/enigma.js#148]
### Description

Hi, this is related to #38.  I'm opening multiple apps via a promise.all and what I'm finding with enigma v2 is that the api is no longer as forgiving as 1.2.1 where openDoc would just open a new websocket for the app and the best practice was to not provide a specific appId.

It seems now that in order for me to open two apps at the same time I cannot use the same session.  I have to open a new session and specify an identity so that enigma will actually open both apps at the same time.

I'm landing on the following:

```
var fs = require("fs");
var qixSchema = require("../node_modules/enigma.js/schemas/12.20.0.json");
var WebSocket = require('ws');
var senseUtilities = require('enigma.js/sense-utilities');


function buildConfig(config,identity)
{
    var newConfig = {
        host: config.engine.hostname,
        port: config.engine.port,
        identity: identity
    }
    return senseUtilities.buildUrl(newConfig);
}

function enigmaInstance(config, identity) {
    var enigmaInstance = {
        schema: qixSchema,
        url: buildConfig(config,identity),
        createSocket(url) {
            return new WebSocket(url, {
                ca: [fs.readFileSync(config.certificates.root)],
                key: fs.readFileSync(config.certificates.client_key),
                cert: fs.readFileSync(config.certificates.client),
                headers: {
                    'X-Qlik-User': "UserDirectory=" + config.engine.userDirectory + ";UserId=" + config.engine.userId
                },
                rejectUnauthorized: false
            });
        }
    };
    return enigmaInstance;
}


//module.exports = buildConfig;
module.exports = enigmaInstance;

```

and then this:

```
Promise.all(docList.map(function (doc) {
var session = enigma.create(enigmaInstance(config,doc));

        session.open()
        .then(function (global) {
            return global.openDoc(doc, '', '', '', false)

        })
        .then(function (app) {
            console.log("app Opened");
            return app.getAppLayout();
        })
        .then(function (layout) {
            console.log(layout.qTitle);
            return;
        })
        .then(function () {
            session.close()
                .then(function () {
                    console.log("session closed.")
                })
        })
        .catch(function (error) {
            console.log(error);
        })
}))
```

Is there a way to use the same app and close the app so I can just open a new one when done?  Or is this the best way now with v2?

### Steps to Reproduce

To get the App already Open message perform the following:

enigmaInstance Code
```
var fs = require("fs");
var qixSchema = require("../node_modules/enigma.js/schemas/12.20.0.json");
var WebSocket = require('ws');

function enigmaInstance(config) {
    var enigmaInstance = {
        schema: qixSchema,
        url: "wss://" + config.hostname + ":" + config.port + "/app/engineData",
        createSocket(url) {
            return new WebSocket(url, {
                ca: [fs.readFileSync(config.certificates.root)],
                key: fs.readFileSync(config.certificates.client_key),
                cert: fs.readFileSync(config.certificates.client),
                headers: {
                    'X-Qlik-User': "UserDirectory=" + config.engine.userDirectory + ";UserId=" + config.engine.userId
                },
                rejectUnauthorized: false
            });
        }
    };
    return enigmaInstance;
}

module.exports = enigmaInstance;
```

test code
```
var enigma = require('enigma.js');
var enigmaInstance = require("./enigmaInstance");
var Promise = require("bluebird");
var config = require("../config/config");

//Add your doc guids here, these are the two I used.
var docList = ["5c83bba5-de4f-4081-80af-a2e9b179a824", "bbdf91f6-e2ca-42eb-9f8b-3453d64f4fb3"]

Promise.all(docList.map(function (doc) {
var session = enigma.create(enigmaInstance(config));

        session.open()
        .then(function (global) {
            return global.openDoc(doc, '', '', '', false)

        })
        .then(function (app) {
            console.log("app Opened");
            return app.getAppLayout();
        })
        .then(function (layout) {
            console.log(layout.qTitle);
            return;
        })
        .then(function () {
            session.close()
                .then(function () {
                    console.log("session closed.")
                })
        })
        .catch(function (error) {
            console.log(error);
        })
}))
```

##### Expected behavior

I expect to just have a session created and destroyed for each app I want to open

##### Actual behavior

I get an app already open error

### Environment

windows server
Node 7.7.4
Visual Studio Code IDE

##### Library
```
[X] Node.js
[ ] Browser
```
##### Operating system
```
[X] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[X] Enterprise
```
### Versions

* Node.js: 7.7.4
* Browser: 
* Qlik Sense: June2017
* Operating system: 2012 R2
* [Other relevant versions]

**Comment by marcusoffesson** [comment]
Hi!

Sorry for the slow response; we are operating in vacation mode.

Can you add a printout of the `OnConnected` notification event and post the output? 

(Simply add this line `session.on('notification:OnConnected', (data) => console.log(data));`
before opening the session.)

**Comment by peol** [comment]
Hi there!

In Sense Enterprise, an _Engine_ session is defined by the `X-Qlik-User`, and the websocket URL (unless `X-Qlik-Session` is used, which may override all other).

You should be able to get unique sessions for two unique apps by defining the app in the URL (which you do in `SenseUtilities.buildUrl`). If you need to open the same app multiple times, the `X-Qlik-User` header needs to be different (or the websocket URL, or both).

It is true that in enigma.js v2, you are in full control of the _Engine_ session, by supplying the URL (this is what all the configuration properties for `SenseUtilities.buildUrl` was in v1). in v1 enigma.js modified your initial configuration with an appId, generates a URL and then fetched a new websocket for it. While convenient in some scenarios, it caused tricky scenarios in regards to parallel apps and session management in others.

We're happily taking suggestions on the SenseUtilities API that may make this scenario a bit more convenient!

**Comment by peol** [comment]
Hi again :)

After discussing this issue with @marcusoffesson this morning, we got a new understanding of your problem. When using [`SenseUtilities.buildUrl()`](https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#senseutilitiesbuildurlconfig), please declare the [`appId`](https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#configuration-1) configuration property to generate a URL to the app you intend to open (we forgot to document it previously!).

Feel free to re-open with additional information if this should not solve your issue.
