### ISSUE TITLE
Expose qix types on qix models

### ISSUE THREAD

**Issue by nilzona** [qlik-oss/enigma.js#15]
When applying a qix mixin you can define the type(s) you want the mixin to be applied to, but if the mixin needs logic depending on the type there is no way of knowing which qix type the generated model has that the mixin gets applied to.

A generated model should expose both the Qix Type and the Custom Type ( qInfo/qType in GenericObject).

**Comment by peol** [comment]
The changes would be somewhere around this logic: https://github.com/qlik-oss/enigma.js/blob/master/src/services/qix/schema.js#L101

If anyone wants to pick it up, just ping us on this issue. We'll get around to this around next week unless it's picked up by someone.

**Comment by peol** [comment]
Fixed in https://github.com/qlik-oss/enigma.js/commit/ef7d1eacb8ec1a3a1410fb4a46d40f492ea7793a
