### ISSUE TITLE
how to use the schema path as variable? 

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#153]
#hi team,

maybe dumb question, but how can I use the schema path in a variable? the code below fails

```
var test = '/node_modules/enigma.js/schemas/qix/12.20.0/schema.json';
const _QIXSchema = require(test);
```
`Error: Cannot find module '/node_modules/enigma.js/schemas/qix/12.20.0/schema.json'`

goal: I want to have one settings file in which I specify all my sense specific stuff like
```JSON
 "private": {
         "QIXSchema": "//node_modules//enigma.js//schemas//qix//3.2//schema.json",
        "certificatesDirectory": "C:\\ProgramData\\Qlik\\Sense\\Repository\\Exported Certificates\\.Local Certificates",
        "SenseServerInternalLanIP": "localhost",
        "useSSL": false,
        "passphrase": null,
        "authentication": "header",
        "virtualProxy": "hdr",
        "headerKey": "hdr-usr",
        "headerValue": "QTSEL\\mbj",
        "isSecure": true,
```

thanks

**Comment by marcusoffesson** [comment]
It looks like you are using an absolute path. Could this be the issue?
(Also, it should be possible to omit the `node_modules` part.)

**Comment by peol** [comment]
Hi!

As mentioned above, it looks like you are using an absolute path on your file system (`/node_modules` is equal to `C:/node_modules`). You may use it like this instead:

```js
const schemaPath = 'enigma.js/schemas/12.20.0/schema.json';
const schema = require(schemaPath);

```
