### ISSUE TITLE
simple examples missing

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#154]
Hi, maybe because the links are dead, so I can't see if its already there, but I really would like to see simple code pieces (so not complete angular apps) that demonstrate how to

* create app
* create a chart
* create a table
* sort a table
* get a list of values out of an app
* get a table out of an app
* create a custom viz (d3) using enigma

Also I miss a piece of text that explains that apparently we have a new version of enigma? I see "migration"?

thanks

**Comment by marcusoffesson** [comment]
[These](https://github.com/qlik-oss/enigma.js/issues?q=is%3Aissue+is%3Aopen+label%3Aexample) are the examples that we have in scope for v2.
