### ISSUE TITLE
Unclear what the mapping between schema's and Qlik sense versions is

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#155]
Since the june release its unclear which version of enigma you need to use, also it might be better to include a chapter in the readme with a mapping table. (june != 12....)

and the june release is called: 11.1.1.1.... and I don't see 11 in the enigma schemas

**Comment by QHose** [comment]
I see its documented in the deep dive schema section, so better to put in this in the readme, all in one page. Also can't we make a function that autodetects the sense version and loads the correct schema?

**Comment by marcusoffesson** [comment]
I agree, we should improve documentation, possibly by adding a mapping table.

Regarding auto detection of schema version; we've discussed the possibility of fetching the schema from the server (via HTTP REST, not over the WebSocket). However, this is not a silver bullet as you will still have to know which API version your program is targeting (e.g. which methods are available, etc.).

**Comment by peol** [comment]
Hi. Auto detection is something we've wanted for a long time but it gets tricky quite fast, but we are still planning on doing a proper investigation of it.

As to identifying which schema you _need_, it's more about what you plan on using in the QIX Engine API. If you upgrade the QIX Engine you communicate with, you may also have to bump the schema you use in your application. I'll move the schema explanation we have into the root readme as a table.
