### ISSUE TITLE
Getting started is too difficult: unclear what the URL is

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#156]
Hi,

Can you add more descriptions on what the URL is? 

```
const session = enigma.create({
  schema,
  url: 'ws://localhost:9076/app',
  createSocket: url => new WebSocket(url),
});
```

e.g. my qlik sense host? or my host:4747 (the engine API port) etc... what is the /app at the end? prefer to refer to standard installation ports here so people understand it.

Also I get this error:
```
I20170729-12:04:29.056(2)? enigma is:  Registry {
I20170729-12:04:29.058(2)?   services:
I20170729-12:04:29.059(2)?    KeyValueCache {
I20170729-12:04:29.060(2)?      entries:
I20170729-12:04:29.061(2)?       { qix: [Function: bound connect],
I20170729-12:04:29.062(2)?         rest: [Function: bound connect] } } }
W20170729-12:04:29.065(2)? (STDERR) error in reloadAppAndReplaceScriptviaEngine via Enigma.JS, [TypeError: enigma.create is not a function]
```

**Comment by QHose** [comment]
Also the example on https://github.com/qlik-oss/enigma.js/blob/master/examples/complete/car-models/src/app.js uses a complete different approach...

```
      enigma.connect(config).then((qix) => {
        this.connected = true;
```

**Comment by QHose** [comment]
ok, even though I tried to update, my project enigma.js files where still on 1.3. Maybe nice to explain how to upgrade in the manual like `meteor npm install --save enigma.js@2.0.0-0`

**Comment by QHose** [comment]
The schema is not used here?
```
const enigma = require('enigma.js');
// schemas is flattened:
const schema = require('enigma.js/schemas/3.2.0.json');
// you are now in full control of the websocket URL:
const config = { url: 'ws://localhost:9076/app/123' };
enigma.create(config).open().then((global) => {
  // global === QIX global interface
  global.openDoc('123').then((doc) => {
    // doc === QIX doc interface
  });
});
```
https://github.com/qlik-oss/enigma.js/blob/master/docs/migrate-v1.md#migrating-from-version-1x

**Comment by QHose** [comment]
So there are a lot of examples all doing it a bit different.

**Comment by marcusoffesson** [comment]
The schema is definitely missing in the migration guide. Good catch! I've reported this in #165.

I will close this issue as it's unclear what the actual question/issue is. Please feel free to report new issues, but keep in mind to keep one issue per report. Also, try to be as specific as possible. Before requesting new examples, please have a look at what we have in [scope](https://github.com/qlik-oss/enigma.js/issues?q=is%3Aissue+is%3Aopen+label%3Aexample) for v2:
