### ISSUE TITLE
Root CA needed to connect to engine?

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#157]
We only need the client and cert files to connect to the engine right? in the examples they import the CA as well.

```
createSocket(url) {
                return new WebSocket(url, {
                    key: engineConfig.key,
                    cert: engineConfig.cert,
                    headers: {
                        'X-Qlik-User': `UserDirectory=${process.env.USERDOMAIN};UserId=${process.env.USERNAME}`,
                    },
```

**Comment by QHose** [comment]
Explained in slack: Hi! Are you trying to use QMC-exported certificates against the Sense Proxy, or directly against Engine? I don’t think they’ll work towards (publically-facing) Sense Proxy due to security.


[10:37] 
And are they signed by a known authority? If so, try dropping the `ca: []` configuration when creating the websocket

**Comment by marcusoffesson** [comment]
This is answered as far as I understand?
