### ISSUE TITLE
different schema definitions are used

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#159]
I see multiple usages of the config object, 

some have

`const config = {
            schema:QIXSchema,`

others only `const config = {
            QIXSchema`

so there is something wrong in the docs: https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#configuration

I think the example is wrong

and in the code below its completely different as in the docs
```
const config = {
  schema: qixSchema,
  session: {
    route: 'app/engineData',
    host: 'localhost',
    port: 4747,
  },
  createSocket(url) {
    return new WebSocket(url, {
      ca: [fs.readFileSync(path.resolve(certificateDir, 'root.pem'))],
      key: fs.readFileSync(path.resolve(certificateDir, 'client_key.pem')),
      cert: fs.readFileSync(path.resolve(certificateDir, 'client.pem')),
      headers: {
        'X-Qlik-User': `UserDirectory=${process.env.USERDOMAIN};UserId=${process.env.USERNAME}`,
      },
    });
  },
  listeners: {
    'traffic:*': (dir, data) => console.log(dir, data),
  },
};```
https://github.com/qlik-oss/enigma.js/blob/master/examples/list-apps/index.js

**Comment by marcusoffesson** [comment]
Not sure I fully understand your question. The `schema` property of the config object is mandatory and cannot be omitted.

In the documentation, we are using the shorthand property naming feature of ES2015. Meaning that `const config = { schema, ... }` is equivalent of `const config = { schema: schema, ... }`.

**Comment by peol** [comment]
Please reopen if something else is unclear (as stated by @marcusoffesson we're using ES2015 short-hand declaration)
