### ISSUE TITLE
Missing a public way of closing a session

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/enigma.js#16]
What's the preferred way to safely close the websocket connection?
Will `session.close()` perform any cleanup or should we handle that one our own?

**Comment by peol** [comment]
Yes, that's the current (and I think undocumented) way of doing it, it will trigger internal cleanup in enigma.js.

What do you think? I've been thinking about perhaps an `app.close()` and `global.close()` mixin, but perhaps closing it on `session` is good enough.

**Comment by mindspank** [comment]
My gut feeling says `session.close()` is more obvious. If I would see `app.close()` I would also expect the application to purge from memory server-side

**Comment by peol** [comment]
True, it could also be another method name though, like `app.closeSession()`, we'll look into what's better, there might be other things we'd like to expose on `.session` anyway and in that case it makes more sense to just document the existing method.

**Comment by peol** [comment]
Another reason why we might opt into using a default mixin (`close()` on `Doc` and `Global`): Since we may share the session/websocket between apps and global instances, doing `.session.close()` may break those other instances. Having a mixin that can track instances and close it once it goes down to `0` would solve that.

**Comment by goldbergjeffrey** [comment]
so I posted the question resolved here on another of @mindspank's questions, but now I have another question that may or may not be germain to this thread.  How do I have multiple apps on one session with enigma?  is it just a matter of extending the config and calling the qix function again with the updated config or is there some other magic involved?

**Comment by peol** [comment]
@goldbergjeffrey Hi, see https://github.com/qlik-oss/enigma.js/issues/38#issuecomment-289667037
