### ISSUE TITLE
Diff. between server and desktop

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#160]
Example code should clearly indicate for which system it works and which enigma versions, the examples and docs are not in sync.

**Comment by QHose** [comment]
In the 1.1 docs the examples are very good: https://github.com/qlik-oss/enigma.js/blob/v1.x/docs/qix/configuration.md

**Comment by marcusoffesson** [comment]
The examples are yet to be done. See [here](https://github.com/qlik-oss/enigma.js/issues?utf8=✓&q=is%3Aissue%20label%3Aexample%20) for the planned v2 scope.

Could you please be more specific on what problems you see with the docs? Thanks!

**Comment by peol** [comment]
All examples being produced right now _default to a local Engine (Sense Desktop in your case)_, unless the example explicitly states otherwise: https://github.com/qlik-oss/enigma.js/tree/master/examples#runnable-examples
