### ISSUE TITLE
no clear docs which params are mandatory

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#161]
In the current docs it sometimes mentioned in the text that a parameter is mandatory, maybe better to
* create a separate column for this (mandatory?)
* make this available in the dev-hub (engine api explorer)
* ensure function names are also camelCase in the dev-hub (engine api explorer), or have a selection

E.g
http://help.qlik.com/en-US/sense-developer/June2017/Subsystems/EngineAPI/Content/Classes/AppClass/App-class-CreateConnection-method.htm

this works in de explorer
```{
    "handle": 1,
    "method": "CreateConnection",
    "params": {
        "qConnection": {
            "qId": "",
            "qName": "adf",
            "qConnectionString": "C:\\Users\\Qlikexternal\\Documents\\GitHub\\QRSMeteor\\customerData\\Cartwright, Boyer and Hahn",
            "qType": "folder",
            "qUserName": "",
            "qPassword": "",
            "qModifiedDate": "",
            "qMeta": {
                "qName": ""
            },
            "qLogOn": 0
        }
    },
    "outKey": -1,
    "id": 4
}
```

but the same thing not in enigma (1*)
```
//create folder connection
        var folder = {
            qConnection: {
                "qName": customer.name,
                "qType": "folder",
                "qConnectionString": customerDataFolder
            }
        };
        console.log('folder is ', folder);
        var qConnectionId = await qix.app.createConnection(folder); 
```
```
I20170729-20:39:49.558(2)?    { qName: 'Cartwright, Boyer and Hahn',
I20170729-20:39:49.563(2)?      qType: 'folder',
I20170729-20:39:49.566(2)?      qConnectionString: 'C:\\Users\\Qlikexternal\\Documents\\GitHub\\QRSMeteor\\customerData\\Cartwright, Boyer and Hahn' } }
```

So now I suspect `qLogOn` is causing my issue... mandatory? not mentoined... also the text is not very clear. (the first time I read, second time is ok)

**Comment by QHose** [comment]
No even when I supply all params from the dev-hub it does not work. Also note dev-hub uses 0 for qLogGon and docs refer to a string...

**Comment by marcusoffesson** [comment]
Note that v1 does not support named parameters, meaning that `qConnection` should be omitted. In v2, named parameters are supported and your above example should work!

The engine documentation is quite clear on mandatory parameters. In this case: `qName`, `qConnectionString` and `qType`.

**Comment by peol** [comment]
@QHose enigma.js generates an API based on a QIX Engine schema. Which parameters you need to pass in is owned by the QIX Engine you communicate with. The dev hub is a Qlik Sense project and should have issues filed either through support or on the internal Jira project.
