### ISSUE TITLE
more documentation?

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#164]
hi,

can you make more documentation please on how to interact with engima?

* how can you use the dev-hub engine API explorer?
* the use of the schema
* which params are mandatory? 
* please provide examples of
** create database connection
** create folder
** create contentlibrary
** publish app
** (--> where can we find the other functions available?)

I tried it using the engine api explorer but did not succeed for functions where I had to supply parameters... (next to the fact that is is not camelCase)

thanks

**Comment by marcusoffesson** [comment]
enigma.js is primarily a QIX engine communications library, and as such I'm not sure that it's the right place for your request. I will bring it up with @peol once we are both back in office and update this issue as soon as we've reached a conclusion.

**Comment by marcusoffesson** [comment]
As mentioned earlier, enigma.js is a _engine communications library_ and not a general place for documentation and examples.

From your list, the item that has bearing on enigma is the use of schema. This is already documented [here](https://github.com/qlik-oss/enigma.js/blob/master/docs/concepts.md#schemas-the-qix-interface).
