### ISSUE TITLE
handle:changed/closed not triggered on resume()

### ISSUE THREAD

**Issue by peol** [qlik-oss/enigma.js#172]
I think it sounds reasonable that these events are emitted on the session; today the `resume()` logic directly calls the API's `changed` and `closed` events, bypassing the session making the `handle:changed` and `handle:closed` events on session inconsistent.

```js
const session = enigma.create({
  schema: require('./schemas/12.20.0.json'),
  url: 'ws://localhost:9076/app/engineData',
  createSocket: url => new WebSocket(url),
});

session.on('handle:changed', handle => console.log(`Session: Handle changed: ${handle}`));
session.on('handle:closed', handle => console.log(`Session: Handle closed: ${handle}`));

session.open().then((global) => {
  global.createSessionApp().then((doc) => {
    console.log(`Session: Document id: ${doc.id}`);
    session.suspend().then(() => {
      console.log('Session: suspend() completed');
      session.resume().then(() => {
        console.log('Session: resume() completed');
        session.close().then(() => {
          console.log('Session: close() completed');
        });
      });
    });
  });
```

**Comment by marcusoffesson** [comment]
We've discussed various ways to solve this issue without introducing a circular dependency between `Session` and `SuspendResume`.
The decision is to remove the `handle:*` events on the `Session` instance as they where mainly intended for debug purposes. Tracing handle change/close can be done using the `traffic:received` event instead.
