### ISSUE TITLE
find a way to pass parameters to mixins

### ISSUE THREAD

**Issue by pouc** [qlik-oss/enigma.js#18]
### Description

I have not found yet a way to pass parameters to mixins. Of course it is possible to pass parameters to the mixin functions, but not to the whole mixin.

It would be nice to have for instance the enigma config to be passed as a parameter of the init function

### Steps to Reproduce

```javascript
var mixin = {
    types: ['Doc'],
    init: (args) => {
        console.log(args.enigmaConfig); // <-- config injected here
        mixin.enigmaConfig = args.enigmaConfig // config saved in the mixin object so that it can be reused in the extend functions
    },
    extend: { ... }
}
```

What do you think?

Best

**Comment by peol** [comment]
Hi @pouc. Sorry for the late response! I think this make sense. It should be possible to do today by mapping the property on each mixin in the `mixins: []` configuration parameter, but I think it is a good idea to have an "official" way of accessing the configuration.

**Comment by peol** [comment]
This will be possible in the upcoming major version. Documentation is pending so keep an eye out once it's released :)
