### ISSUE TITLE
enable mixin init to wait upon completion of a promise

### ISSUE THREAD

**Issue by pouc** [qlik-oss/enigma.js#19]
### Description

A mixin could take time to initialize. It would be great if we could return a promise from within the init function to wait upon.

### Steps to Reproduce

```javascript
init: function(args) {
    return args.api.getAppLayout().then((layout) => {
        args.api.layout = layout;
    });
}
```

Thanks

Best

**Comment by peol** [comment]
Hi! This may be troublesome to do, we don't want potential delays of getting an API back from e.g. `app.getObject()` if we can avoid it. There's a way today to intercept responses, and do additional operations (it's not public yet, though), but it's not tied to mixins.

What would be another use-case? I don't really understand why you would need to use the app layout during initialization of a mixin (instead of when you *actually* need it in e.g. a mixin method), could you elaborate it a bit more? :)

**Comment by pouc** [comment]
in this example I need the app ID in a mixin method.

this mixin method is a SDK around QRS API (see [this github repo](https://github.com/pouc/qlik-api-qrs) and [this](https://github.com/pouc/qlik-utils/blob/v3/index.js))

the idea is to call for instance:

```javascript
enigma.getService('qix', config).then((qix) => {
    return qix.global.openDoc('40adf26b-edb2-448d-8787-7fe2f9d23f02');
}).then((doc) => {
    return doc.qrs().delete();
});
```

without a delayed init, the code would look like this instead:

```javascript
enigma.getService('qix', config).then((qix) => {
    return qix.global.openDoc('40adf26b-edb2-448d-8787-7fe2f9d23f02');
}).then((doc) => {
    return doc.qrs();
}).then((qrsDoc) => {
    return qrsDoc.delete();
});
```

which is fine I guess, but more complicated to read IMHO.

**Comment by peol** [comment]
Have you tried to do a mixin on `Doc` for `openDoc`, that does the `doc => doc.qrs()` return so end-users don't have to do the extra promise chain in this case?

Example:

```js
{
  types: ['Doc'],
  override: {
    openDoc: (_openDoc) => _openDoc.then((doc) => doc.qrs())
  }
```

**Comment by pouc** [comment]
Great idea! Is there a prefered way to store objects that would be shared between mixin methods?

Is this recommanded?

```javascript
var mixin = {
  types: ['Doc'],
  extend: {
    qrs: () => {
      return mixin.qrs;
    }
  }
  override: {
    openDoc: (_openDoc, id) => {
      return _openDoc(id)
        .then((doc) => {
          return doc.getLayout()
            .then((layout) => {
              mixin.qrs = doSomething(layout);
            })
            .then(() => {
              return doc;
            });
        });
    }
  }
}
```

**Comment by peol** [comment]
If you avoid arrow functions, your override method's `this` should be the API/model instance, if you need to share instance-specific values. You can also have a cache outside of this logic altogether (e.g. above your `var mixin`), and refer to that whenever your mixin is called.

**Comment by peol** [comment]
Closing this in favor of the discussion above. Let us know if if there are other use-cases that we might solve with something like this.
