### ISSUE TITLE
Missing npm package

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/enigma.js#2]
### Description

Documentation references `npm install enigma.js` at https://github.com/qlik-oss/enigma.js/blob/master/docs/README.md

However the current enigma.js package on NPM is a placeholder repo without code.
https://www.npmjs.com/package/enigma.js

### Steps to Reproduce

1. Run `npm install enigma.js`
2. Sad emoji face

**Comment by peol** [comment]
We're aware. :) All newly open-source libraries will be be published to npm tomorrow (thursday). It's been an intense day and we want to make sure everything works as it should (builds, testing, etc.) before we release it to npm.

**Comment by peol** [comment]
`enigma.js@1.0.0` published this morning. Enjoy :)
