### ISSUE TITLE
npm build run on windows / linebreakstyle

### ISSUE THREAD

**Issue by konne** [qlik-oss/enigma.js#21]
### Description

error on npm build run on windows.

... error Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

please add to the .eslintrc
    linebreak-style: ["warn", "unix"]
this means that the sytem just warn and doesn't produce an error.
I see no issue out of the different linebreakstyle

### Steps to Reproduce

1. git clone
2. npm install
3. npm build run

##### Expected behavior

thats working, maximal warnings

##### Actual behavior

build fail

##### Library

* [ x] Node.js
* [ ] Browser

##### Operating system

* [x ] Windows
* [ ] OSX
* [ ] Linux

##### Qlik Sense

* [ ] Desktop
* [ ] Enterprise

### Versions

* Node.js: 7.6.0
* Browser: -
* Qlik Sense: - 
* Operating system: Windows 10

**Comment by pouc** [comment]
Hi,

I have had the same issue.

You can work around this by disabling linebreak conversion on your git install before clone/checkout:

`git config --global core.autocrlf false`

IMHO having multiple linebreak styles is not a good thing.

Would that help?

Best

**Comment by peol** [comment]
Hi! As @pouc mentions, it's a configuration thing that can be done on a global level (like the example above), or on a repo level. We are using the airbnb style guidelines and try to avoid overriding it if possible (to reduce [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding)). We currently do a few overrides, but it's on our to-do list to remove these: https://github.com/qlik-oss/enigma.js/blob/master/.eslintrc#L10

We may want to update our `README.md` to hint how to solve it in your environment, however.

**Comment by konne** [comment]
Hi, please don't update in that case not the Readme. Please update the Contribution.md in the step by step plan.

**Comment by peol** [comment]
Makes sense, thanks :)
