### ISSUE TITLE
add npm package of enigma.js

### ISSUE THREAD

**Issue by konne** [qlik-oss/enigma.js#22]
### Description

please fill the following npm package with live.

https://www.npmjs.com/package/enigmajs

**Comment by axelssonHakan** [comment]
This is the official npm package
https://www.npmjs.com/package/enigma.js

We should remove the other "URL" to avoid misconception

**Comment by konne** [comment]
thx, do you like to close that issue, or let it open as reminder

**Comment by konne** [comment]
please also add a small reference in the read.me or somethere else in the documentation

**Comment by peol** [comment]
We will tag the `enigmajs` module as deprecated (triggering a warning when you install it). We'll close this issue once that's done.

**Comment by peol** [comment]
Package deprecated and should now trigger warnings when installed. Thanks for reporting!
