### ISSUE TITLE
Authentication: Sense using Windows account (NTLM auth)

### ISSUE THREAD

**Issue by theunexpected1** [qlik-oss/enigma.js#223]
I have been trying to use the enigma.js library for authenticating using Windows account (NTLM) but with no success.

Can someone please show a basic example for this? If not an example, any pointer to where I can look for the correct Header / Virtual proxy settings / etc. would be greatly helpful.

We have [Certificates](https://github.com/qlik-oss/enigma.js/issues/126) and [JWT](https://github.com/qlik-oss/enigma.js/issues/190) methods for authentication, but the API I'm building is open for access to public, so I would need user-based / Active Directory login with UserDirectory/UserId/Password criteria.

**Comment by peol** [comment]
Hi @theunexpected1.

We need to understand your use case a little bit better.

* Can you describe what it is that is not working in more detail?
* Are you using enigma.js in your web application (browser), and if so, do you host it outside of the Sense environment?

In general, enigma.js itself does not provide any way of authenticating against deployments (see [High-level concepts page](https://github.com/qlik-oss/enigma.js/blob/master/docs/concepts.md#authentication)), but we do provide a couple of examples for Sense as you have mentioned because it is the most common ways of authenticating through Node.js (programmatic APIs).

**Comment by theunexpected1** [comment]
Hi @peol,

Thanks for your response.

I am basically creating a Telegram Bot which connects to an API (let's say on X server), which in turn connects to the Qlik Sense server (on Y server).
Since the call to the Qlik Sense is made from outside the Sense Environment, I require authentication.

However, you can imagine that the nature of a bot would be that it's accessible publically with the bot's handle (@someBot); due to this I would require authentication by Active Directory where the user can send some command to the bot.
Eg: `/connect someDirectory/someJonDoe myP@ssw0rd`

I understand that enigma.js is merely providing examples that make use of the Qlik Sense APIs, and that's why I would appreciate any advice on how to achieve the above authentication.

**Comment by peol** [comment]
Hi! Sounds a like a fun project (albeit, sharing their passwords over a chat client scares me a bit) :sweat_smile:

We have discussed internally and decided to not provide an NTLM example in this repo. However, we did come up with a potential solution for you using JWT:

1. Let the user supply their AD credentials
2. Validate it using an NTLM library like https://github.com/einfallstoll/ntlm-ad-client
3. If NTLM auth was successful, generate a JWT token with their directory/userid credentials
4. Pass JWT into Sense in websocket header in enigma.js

I wish you good luck on your project!

**Comment by theunexpected1** [comment]
Hey @peol, thanks for the quick turnaround!

I agree with you, sharing password over a client is a bit unorthodox, and so I am trying the OAuth method (if possible) - just as Youtube does it on Telegram.

The solution you suggested looks elegant, but I am still having trouble with the initial steps -
 validating the AD credentials via the NTLM library you suggested.

I am not able to successfully set up the LDAP-enabled Virtual Proxy on the QMC.
Similar to the library you shared, this one is also doing the job - https://github.com/johsund/Qliklogin#configjs - is there any way I can get some help in setting up the QMC for these LDAP parameters including ports and any other configurations?

What I did so far is
- Exposed the port 389 on the QMC->Engine for login via `LDAP://{dirname}:389`
- Added to the Virtual proxy's whitelist the DNS name for the server where I'm running [this library](https://github.com/johsund/Qliklogin)-based login page - [Screenshot](http://phtr.co/2gJkKhx)
- Added a User Directory Connector with path `ldap://{dirname}` - [Screenshot](http://phtr.co/2gKqhUV)

Please any advice is welcome, also let me know if I am bothering here with irrelevant questions.
Again, thanks for the help till now!

**Comment by peol** [comment]
Hi @theunexpected1, for general Qlik API discussions/help you may want to try our Qlik Branch slack team over here, it's quite an active community: http://branch.qlik.com/slack

**Comment by theunexpected1** [comment]
Alright, thanks @peol!
