### ISSUE TITLE
registration of mixins in different ways

### ISSUE THREAD

**Issue by thomashaenig** [qlik-oss/enigma.js#227]
Hi,
at this point you can give only an array to the config.mixin to registrate mixins. It would be great to give an Array of Arrays to config.mixins. In this way you can simply push another array of mixins to the standard mixin array from halyard.

Greatings Thomas

**Comment by marcusoffesson** [comment]
Hi @thomashaenig!

I think you are asking for runtime registration of mixins, right? See #218.

**Comment by thomashaenig** [comment]
Hi,
Thanks for your quick answer. I would like to insert the following structure (cause of frameworks I use)
Mixin: [minin-1, [mixin-2, mixin-3]]

At this point I do have a function which creates me the plain structure like [minin-1, mixin-2, mixin-3]. Maybe it would be easier if the mixin property could handle complex structures by them self. 
Load the mixin during runtime is no solution for me, cause I do need the mixin during the constructor of my controller object.

**Comment by peol** [comment]
You could do:

```
const config = { mixins: [myMixin] };
const arrayOfMixins = [otherMixin, thirdMixin];
config.mixins.push(...arrayOfMixins);
// or:
config.mixins.push.apply(config.mixins, arrayOfMixins);
```

**Comment by peol** [comment]
We believe this is working as intended, there are different options available to you already :)
