### ISSUE TITLE
releases of enigma

### ISSUE THREAD

**Issue by konne** [qlik-oss/enigma.js#23]
### Description

the releases.zip just contains the soure of the github repo

### Steps to Reproduce

1. https://github.com/qlik-oss/enigma.js/releases

##### Expected behavior

what the zip contains the /dist/ directory what is compiled with npm run build

**Comment by peol** [comment]
We are not tracking built files in version control, and only tag (with annotation) releases today to reduce overhead.

The actual run-time library is available on npm:
https://www.npmjs.com/package/enigma.js

If you want to use it without npm, there are services like unpkg.com, example:
https://unpkg.com/enigma.js@1.0.1/dist/enigma.min.js
