### ISSUE TITLE
v1 not authenticated when supplying valid ticket

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#236]
hey guys, using enigma 1, using node client side, what is wrong with this config? I don't get an authenticated session when I supply a valid ticket in the config object.

So I first get a ticket on the client, then I try to make the config object, then I setup a enigma connection.

![image](https://user-images.githubusercontent.com/12411165/30261210-bd96a434-96cb-11e7-9b65-31cf49434489.png)

```
 const enigmaConfig = {
        schema: qixschema,
        appId: appId,
        session: { //https://github.com/qlik-oss/enigma.js/blob/master/docs/qix/configuration.md#example-using-nodejs
            host: senseConfig.host,
            prefix: Meteor.settings.public.slideGenerator.virtualProxy,
            port: senseConfig.port,
            unsecure: true,
            urlParams: {
                qlikTicket: ticket
            }
        },
        //http://help.qlik.com/en-US/sense-developer/June2017/Subsystems/ProxyServiceAPI/Content/ProxyServiceAPI/ProxyServiceAPI-Msgs-Proxy-Clients-OnAuthenticationInformation.htm
        // listeners: {
        //     'notification:OnAuthenticationInformation': (authInfo) => {
        //         // console.log('authInfo', authInfo)
        //         if (authInfo.mustAuthenticate) {
        //             location.href = authInfo.loginUri;
        //         }
        //     },
        // }
    };

    console.log('enigmaConfig', enigmaConfig)

    enigma.getService('qix', enigmaConfig)
        .then(qix => {
            console.log('user is authenticated in Qlik Sense. QIX object:', qix);
            Session.set('userLoggedInSense', true);
            Meteor.clearInterval(intervalId);
        }).catch((error) => {
            console.info('info: No QIX connection for user, user not yet able to connect to the app via the enigma.js: ', error);
        });
} 
```
So my understanding was, that if you supply a valid ticket you are immediately authenticated in one go... ?

Question 2: I also noticed (now commented out in the config), that my page does not reload when the user is not yet authenticated, so my understanding is, that enigma looks in (or gets) the authentication redirect url in the virtual proxy?

**Comment by marcusoffesson** [comment]
Hi @QHose!

Your config look alright. Can you please provide output? E.g. by printing put notification messages and or websocket traffic.

**Comment by QHose** [comment]
hi, sorry, tried to find, but how can I enable the logging in my config object?

**Comment by marcusoffesson** [comment]
Hi @QHose,

Notification messages (v1):
```js
const config = {
  schema,
  appId,
  ...,
  listeners: {
    'notification:*': (event, data) => console.log(event, data)
  },
});
```

Websocket traffic (also v1):

```js
const config = {
  schema,
  appId,
  ...,
  handleLog: (message) => console.log(message),
});
```

**Comment by QHose** [comment]
```
client received ticket from server:  46SeD-qN-oWEg.L1
landingPage.js:156 enigmaConfig {schema: {…}, appId: "dcfb96da-cac0-435a-85de-7f0f7910488e", session: {…}, listeners: {…}, handleLog: ƒ}appId: "dcfb96da-cac0-435a-85de-7f0f7910488e"handleLog: ƒ (message)listeners: {notification:*: ƒ}schema: {structs: {…}, enums: {…}}session: host: "QLIK-AB0Q2URN5T"port: 81prefix: "presentationsso"route: ""secure: falsesuspendOnClose: falseunsecure: trueurlParams: {qlikTicket: "46SeD-qN-oWEg.L1"}__proto__: Object__proto__: Object
landingPage.js:144 {msg: "Sent", connection: 1, data: {…}}
landingPage.js:142 OnAuthenticationInformation {loginUri: "http://localhost:3000/presentationsso?proxyRestUri…%2f&targetId=0eba3059-9af0-414d-9d41-d063be11cd62", mustAuthenticate: true}loginUri: "http://localhost:3000/presentationsso?proxyRestUri=https%3a%2f%2fqlik-ab0q2urn5t%3a4243%2fqps%2fpresentationsso%2f&targetId=0eba3059-9af0-414d-9d41-d063be11cd62"mustAuthenticate: true__proto__: Object
landingPage.js:164 info: No QIX connection for user, user not yet able to connect to the app via the enigma.js:  {code: -1, message: "Socket closed"}code: -1message: "Socket closed"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
```

**Comment by QHose** [comment]
not sure what is happening... Does enigma set a session cookie after I supplied the ticket? I see now the message it is connected, but my iframe (with the hub in it) still triggers an authentication redirect...

**Comment by marcusoffesson** [comment]
You are not authenticated.

In this case, the Qlik Sense Proxy accepts your incoming websocket connection, sends the `OnAuthenticationInformation` message and then immediately closes the websocket. See [`notification:<name>`](https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#event-notificationname) (make sure to follow the link to [Messages from the QPS to clients](https://help.qlik.com/en-US/sense-developer/June2017/Subsystems/ProxyServiceAPI/Content/ProxyServiceAPI/ProxyServiceAPI-Msgs-Proxy-Clients.htm)).

**Comment by QHose** [comment]
Thanks! So if I supply a ticket via enigma I will also get a session cookie?


Regarding getting a session first via a plain Jquery http get I saw I had used a wrong example code. I used ticket=abc instead of qlikTicket=abc

**Comment by QHose** [comment]
I was using the wrong proxy to request a ticket, now it all works, thanks for your help.

![image](https://user-images.githubusercontent.com/12411165/30326026-66951510-97c7-11e7-82ad-e1c4fd8007ba.png)

**Comment by QHose** [comment]
and I also get a session cookie
![image](https://user-images.githubusercontent.com/12411165/30326058-7e28143e-97c7-11e7-93b9-cd71ceceba3e.png)
