### ISSUE TITLE
App reload doesn't work

### ISSUE THREAD

**Issue by dmcfaul** [qlik-oss/enigma.js#24]
### Description

I've created an app reload script using enigma.js that should open the app and reload it. I receive successful connection and responses, however the data in the app doesn't reload. I can look up the app in the QMC and see the last reload timestamp matches when I ran my script, but the app doesn't have new data. The app does have new data if I run a reload Task for the specific app in the QMC.
My script is attached at the bottom of this text block
### Steps to Reproduce

1. Use attached node script to reload an app by supplying it with an app id. E.g. `node reloadApp.js {appId}`
2. Check if new data was added to app in qlik. (fails)
3. Check last reload time in QMC for the app. Should match when you ran the reloadApp script.

##### Expected behavior

Reload app data.
##### Actual behavior

Data was not reloaded.
##### Library

* [ x] Node.js
* [ ] Browser

##### Operating system

* [ ] Windows
* [ ] OSX
* [x ] Linux

##### Qlik Sense

* [ ] Desktop
* [x ] Enterprise

### Versions

* Node.js: 
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

[reloadApp.txt](https://github.com/qlik-oss/enigma.js/files/794590/reloadApp.txt)

**Comment by konne** [comment]
Hi,
please test to add a doSave() after the reload.
bye Konrad

**Comment by dmcfaul** [comment]
That fixed the issue, thanks!
It seems the qlik docs aren't clear on this point:
https://help.qlik.com/en-US/sense-developer/3.2/Subsystems/APIs/Content/MashupAPI/Methods/doReload-method.htm

The doReload doesn't mention that you'll need to do a doSave as well. 
For posterity, the doSave doc shows it in the promise of a doReload:
https://help.qlik.com/en-US/sense-developer/3.2/Subsystems/APIs/Content/MashupAPI/Methods/doSave-method.htm

**Comment by konne** [comment]
@dmcfaul first: I think this is not the right place for EngineAPI discussion. Please post here https://community.qlik.com/community/qlik-sense/integration-%26-extensions
second: the api is correct and sometime you want just a reload without a save. If you would access the engine an fetch data, you would see that they are already in the memory
