### ISSUE TITLE
Sense authenticate using certificates: 'Socket closed' error

### ISSUE THREAD

**Issue by Turiddru** [qlik-oss/enigma.js#241]
### Description

Hi all!
I'm trying to authenticate using certificates to qlik sense server. 
I'm following [this](https://github.com/qlik-oss/enigma.js/blob/v2.0.0/examples/authentication/sense-using-certificates/certificates.js) example.
The userId i'm using has RootAdmin role, and has access to all qlik apps.

It seems that session is opened (I receive the log message `Session was opened successfully`), but `global.getDocList()` returns an error:
`Failed to open session and/or retrieve the app list: { code: -1, message: 'Socket closed' }`

I added a listener to the 'closed' event: 
`session.on('closed', (a) => console.log('Session closed: ',a));`
and the log message is the following:
```
Session closed: CloseEvent {
  target:
   WebSocket {
     domain: null,
     _events:
      { open: [Object],
        close: [Object],
        error: [Object],
        message: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 3,
     bytesReceived: 0,
     extensions: {},
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _finalizeCalled: true,
     _closeMessage: null,
     _closeTimer: null,
     _closeCode: 1006,
     _receiver:
      Receiver {
        _binaryType: 'nodebuffer',
        _extensions: null,
        _maxPayload: 0,
        _bufferedBytes: 0,
        _buffers: null,
        _compressed: false,
        _payloadLength: 0,
        _fragmented: 0,
        _masked: false,
        _fin: false,
        _mask: null,
        _opcode: 0,
        _totalPayloadLength: 0,
        _messageLength: 0,
        _fragments: null,
        _cleanupCallback: null,
        _hadError: false,
        _dead: true,
        _loop: false,
        onmessage: null,
        onclose: null,
        onerror: null,
        onping: null,
        onpong: null,
        _state: 0 },
     _sender: null,
     _socket: null,
     _ultron: null,
     protocolVersion: 13,
     _isServer: false,
     url: 'wss://---/app/---',
     _req: null },
  type: 'close',
  wasClean: false,
  reason: '',
  code: 1006 }
```

There are other configurations to provide on qlik qmc? What means error code 1006? What am I doing wrong?

### Steps to Reproduce
1) exports pem certificates from qlik qmc
2) execute the example (https://github.com/qlik-oss/enigma.js/blob/v2.0.0/examples/authentication/sense-using-certificates/certificates.js)

##### Expected behavior

1- Log message: "Session was opened successfully"
2- List of the apps the user can open.

##### Actual behavior

1- Log message: "Session was opened successfully"
2-  Log message: "Failed to open session and/or retrieve the app list: { code: -1, message: 'Socket closed' }"

### Environment
Qlik Sense Enterprise June 2017
QIX Engine 12.20.10
enigma.js 2.0.2

**Comment by peol** [comment]
Hi @Turiddru. Have you modified the example for your Sense Enterprise installation? As mentioned in the example readme you need to modify e.g. user directory/id here: https://github.com/qlik-oss/enigma.js/blob/v2.0.0/examples/authentication/sense-using-certificates/certificates.js#L22 so it matches a Sense Enterprise user that has access to your deployment.

Could you please share the output after adding this line (before line 49):
`session.on('traffic:*', console.log);`

**Comment by Turiddru** [comment]
Yes, I have modified userId and user directory as well as host, port and appId.
Here is the output of the `traffic:*` listener:
```
sent { delta: true,
  method: 'GetDocList',
  handle: -1,
  params: [],
  jsonrpc: '2.0',
  id: 1 }

received { jsonrpc: '2.0',
  method: 'OnAuthenticationInformation',
  params:
   { loginUri: 'https://---:4244/form/?targetId=XXX-XXX-XXX-XXX-XXX',
     mustAuthenticate: true } }
```

**Comment by peol** [comment]
The authentication notification you receive is sent by the Sense Proxy, the certificate approach does not  support using the root certificates against the public Sense Proxy due to security reasons, you need to connect to an Engine directly by opening up the _Engine_ port. If you want to go through the Sense Proxy (because of load-balancing, etc.) we recommend you use the JWT or ticketing approach.

**Comment by Turiddru** [comment]
It works connecting directly to the Engine port (4747)! Thank you very much!
If I wanted to connect to the proxy using the ticketing approach what would be the correct way? Have you got have some examples?

**Comment by peol** [comment]
No, so unfortunately we do not have an example on ticketing yet (there's an issue #125 but not prio'd). The JWT approach is far easier to use so we happily promote that instead :) You can find that here: https://github.com/qlik-oss/enigma.js/tree/master/examples/authentication/sense-using-jwt#authentication-qlik-sense-json-web-token-jwt

**Comment by kashanmemon** [comment]
> No, so unfortunately we do not have an example on ticketing yet (there's an issue #125 but not prio'd). The JWT approach is far easier to use so we happily promote that instead :) You can find that here: https://github.com/qlik-oss/enigma.js/tree/master/examples/authentication/sense-using-jwt#authentication-qlik-sense-json-web-token-jwt

I have visited the engima.js examples on github and it is missing authentication for ticketing. We have a use case where we have to use virtual proxy configured as ticketing when connecting to the engine. You have mentioned in your comment that there's an issue #125 but not prio'd for ticketing authentication. I visited issue #125 where you have stated the path /examples/authentication/sense-ticketing but I was not able to find it. Can you please send me the example for this?
