### ISSUE TITLE
Hosted versions on CDNs

### ISSUE THREAD

**Issue by seriousben** [qlik-oss/enigma.js#243]
### Description

Would be awesome if could have hosted versions of enigma hosted on 3rd party CDNs. 

Maybe something like: https://www.jsdelivr.com/ or https://github.com/cdnjs/cdnjs

This would allow for an easy way to get started.

**Comment by peol** [comment]
Hey, we've had this question before and referred to e.g. https://unpkg.com/ which enables you to pull in resources from any npm package.

Here's 2.0.2: https://unpkg.com/enigma.js@2.0.2/enigma.js

Not a CDN per se, but good enough for hackathons, jsfiddles, etc?

**Comment by MartinKolarik** [comment]
jsDelivr can serve anything from npm now too: https://www.jsdelivr.com/package/npm/enigma.js

**Comment by peol** [comment]
@MartinKolarik Awesome, thanks for the update!

@seriousben I guess we're all set here :)

**Comment by MartinKolarik** [comment]
👍 consider adding the correct link to readme so that people can find it more easily in the feature.
