### ISSUE TITLE
Ideas around schemas

### ISSUE THREAD

**Issue by konne** [qlik-oss/enigma.js#249]
Please think of changing the shema.json handling.

* in 2 year you will have a bunch of files in the shema directory
* you have to first to connect to the engine to fetch the correct version
  after that you have to go back and load the right shema to connect
  again
* I know this is a chicken-and-egg problem, but would it be
not better the the engine or more generalized the websocket endpoint
can deliver the shema file and than the enigma.js just grabs it and
use it?

**Comment by peol** [comment]
Hi!

* I don't see this as a big problem, what's your concern?
* If you absolutely need to run the same schema as the QIX Engine you talk to, yes :) The API is very compatible between versions though and in reality I don't think you'd see any real issues staying on a bit older version of the API (in fact, if you use the QIX API in your web application, automatically fetching the API based on Engine version could be a bad idea)

In any case, we are looking into ways of supporting this without the obvious drawbacks (HTTP caching, breaking APIs, latency, etc.); but we ask you to be patient :)

**Comment by konne** [comment]
Hi
I don't see a big problem, it was just something that came into my mind.
I know that the API is very constant, but I like the idea to have compatibility mixins,
so that I don't have to take care of the engineAPI version in my product. I can
just load the correct shema + a transform mixin.

>..to be patient 
Great to here that you have it already mind. In my eyes it would be great if the engine can deliver it as a gernal defined function, like you (qlik) adds to all apis the open-api endpoints. And with websockets you also have no http-caching issues.

If you like you can close the topic or let it open for further discussion.

**Comment by peol** [comment]
>  engineAPI version in my product. I can just load the correct shema + a transform mixin

Would love to support that scenario, the problem still stands though; how would you know which transform mixins to load if the schema is loaded dynamically—you'd have to have bundled a bunch of forwards/backwards compatible mixins and apply them in runtime then?

> In my eyes it would be great if the engine can deliver it as a gernal defined function, like you (qlik) adds to all apis the open-api endpoints. And with websockets you also have no http-caching issues

If the schema was delivered from a QIX method (over websockets), you can never cache it and will have to download ~55kb+ each (browser) session you open. OpenAPI spec is an interesting idea and might be something we'd like to explore further, the problem here is that the QIX API doesn't really fit very well with the REST-ish format of OpenAPI :)

**Comment by konne** [comment]
> Would love to support that scenario, ...
So we are already two 👍 

First I see this only as a problem of me and not of you (as qlik).
So if I have have a toolchain that allows me do this,
I can first start to develop the for me needed converters and
don't have to deliver a 100% solution.
So I see this like mixins in a separate repo there step by step functionality is
added.
Second like you mentioned there are not many changes, and changes like the new
introduced "GetTreeData..." everybody has to think if this need really backward
compatible.

>schema
First, we need a concept of combined shemas, there lines are marked in which version they are valid, because 99% auf all schema files are the same
Second, this can be even a concept if you ask the engine that the engine can deliver just the difference so that if you have a compiled / included / per rest loaded schema the difference is onyl very small.

**Comment by cookiejest** [comment]
The versions of the API should be shipped with the product and passed as a parameter when connecting to the engine. It doesn't make sense to have all these separate schema. It is development overhead that should be handled gracefully by the engine itself!

**Comment by peol** [comment]
Any schema-related enhancements will be considered after #469 has been implemented. Closing this for now.
