### ISSUE TITLE
Publish latest schemas to NPM?

### ISSUE THREAD

**Issue by skokenes** [qlik-oss/enigma.js#250]
Currently in the enigma.js NPM package, the latest qix engine schema that is shipped is 12.20.0 (this is package version 2.0.2).

You recently added the schema for 12.34.11 to this repo. Can you publish this latest schema to NPM?

**Comment by peol** [comment]
Hi, we are planning on releasing 2.1 soon (we merged #246 just a few minutes ago) where the new schema will be included so it's definitely coming. If you need the schema today I recommend you download it from here and plug it into your project manually :)
