### ISSUE TITLE
typescript files

### ISSUE THREAD

**Issue by konne** [qlik-oss/enigma.js#26]
### Description

I'm generating at the moment for all qlik APIs / js lib typescript defintion files.
For npm packages there are two possibilities:

1. add them to the main npm package
2. add them to https://github.com/DefinitelyTyped/DefinitelyTyped

Should I take possibility 1 and deliver them to you, or take 2?

**Comment by peol** [comment]
We have discussed this earlier internally, but we never came to a conclusion. My personal preference would be to keep stuff like this out of the repository but I'll request others feedback here.

**Comment by peol** [comment]
Hi again. We've had the discussion internally and decided that we will not include type definitions (and similar implementations) inside this git repo. Main reason is maintainability and that enigma.js supports multiple Engine/REST services (i.e. enigma.js is not tied to a specific version of a Qlik product).

In your case, 2) seems like a great option!

**Comment by konne** [comment]
no prob, I just want to ask

**Comment by rjriel** [comment]
@konne is this something you gave up on or is it still a work in progress?

**Comment by konne** [comment]
@rjriel only engimaJS is missing. I already have completed and documented the:
1. https://www.npmjs.com/package/@types/qlik-visualizationextensions
  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/qlik-visualizationextensions/index.d.ts
2. https://www.npmjs.com/package/@types/qlik-engineapi
   https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/qlik-engineapi/index.d.ts
and they are working great. They already updated for 12.20.0 / June2017.

EnigmaJS are onle some functions and I will complete them now after 2.0 is released.
Maybe next week.

**Comment by rjriel** [comment]
@konne Great to hear!! I'm looking at converting Qlik Branch to Angular and this will definitely make my life easier.

**Comment by konne** [comment]
@rjriel see at this project https://github.com/q2g/q2g-ext-selector

**Comment by konne** [comment]
@rjriel we working at the moment hard on a library that combines extension / angular1.x and angular2+ visualisation element see also https://github.com/q2g/daVinci.js
At the moment angular 2+ is missing but we will add this in the next weeks, if you like it would be great if you can also contribute or we can share ideas / experiences
