### ISSUE TITLE
Example: Parameter passing

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#269]
### Description

Since enigma.js v2.0.0 it's been possible to pass parameters either by name or by position. To showcase this feature a runable example is needed! (Documentation [here](https://github.com/qlik-oss/enigma.js/blob/master/docs/concepts.md#schemas-the-qix-interface))

Path: /examples/basic/parameters

**Comment by konne** [comment]
@marcusoffesson: can this get closed?

**Comment by marcusoffesson** [comment]
@konne Yes, my bad, I should have closed it when @thomashaenig's PR was merged.

**Comment by marcusoffesson** [comment]
Fixed by @thomashaenig in #297! Thanks for contributing!
