### ISSUE TITLE
Packaged mixin: `getObject` cache

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#270]
### Description

A client-side cache of generated APIs. Decreases latency, bandwidth, and memory. Would support all QIX get methods:

```
* getObject
* getBookmark
* getDimension
* getMeasure
* getVariableById
* getVariable
* getVariableByName
* getField
```

**Comment by konne** [comment]
what is the difference to #275? Does it more make sense to handle the caching in one library?
Is it possible to get a 'changed' on for example an Variable?
It't tricky if someone for example change the name or a variable so that you also have to change the key on an object.

**Comment by marcusoffesson** [comment]
Hi @konne!

The difference is that this mixin keeps track of generated APIs (objects) while #275 is about keeping track of each object's state. I think it makes sense to have this and #275 as separate mixins as they can be used independent of each other.

**Comment by peol** [comment]
Tracked in #220 , we'll re-open these issues once we can work on them.
