### ISSUE TITLE
Packaged mixin: Pending call cache

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#271]
### Description

Given a specific handle, specific QIX method, and specific QIX method parameters, we can join calls to QIX Engine. Decreases latency, bandwidth, memory, and potential computing in QIX Engine.

**Comment by konne** [comment]
please can you provide an sample

**Comment by peol** [comment]
Tracked in #220 , we'll re-open these issues once we can work on them.
