### ISSUE TITLE
Packaged mixin: Normalize `Doc` QIX API

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#272]
### Description

QIX Engine has a slightly different API when talking towards a document than e.g. a generic object. This mixin would normalize the API to look identical to generic objects.

```
* getAppProperties -> getProperties
* setAppProperties -> setProperties
* getAppLayout -> getLayout
```

**Comment by konne** [comment]
In which directory you like to get the mixin as PR?
Do you have a prefered name per file?

**Comment by marcusoffesson** [comment]
Hi @konne!

Good question! We've discussed various ideas, but haven't really come to a conclusion. For example, should we have mixins as separate npm-packages (that resides in their own git repositories) or should it be part of the enigma distribution?

For now, I think we can put them in `src/mixins`.

**Comment by konne** [comment]
thanks, I will discuss it with @thomashaenig so that he can add this in the next week

**Comment by marcusoffesson** [comment]
No problem! Also, it's important that the rollup-config and package.json are updated acordingly. From a user perspective, one would like to do:

```js
const mixin = require('enigma.js/mixins/normalize');
```

to import the mixin.

**Comment by peol** [comment]
A this time we have way better documentation (e.g. https://qlikcore.com/services/qix-engine/apis/qix/doc/#getapplayout) that takes care of the Doc interface minor inconsistencies instead. Closing this for now.
