### ISSUE TITLE
Packaged mixin: Garbage collector/memory optimizer

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#273]
### Description

In large web applications there may be times where a lot of large generic object hypercubes are cached client-side. In e.g. mobile that may cause huge slow downs. This mixin would be somewhat configurable, but sport a garbage collector that could be configured to e.g. "clean up generated APIs with no event listeners after X minutes of inactivity".

**Comment by peol** [comment]
Tracked in #220 , we'll re-open these issues once we can work on them.
