### ISSUE TITLE
Packaged mixin: Access global/doc from generated APIs

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#274]
### Description

The idea here is that, for convenience, expose the QIX Global API as well as the corresponding QIX Doc API on any generated APIs. Example:

```js
function externalFunction(api) {
  api.doc.getDimension('some-dimension').then(dimensionApi => {
    // do something with `api` and `dimensionApi`
  });
}

doc.getObject('some-object').then(generatedApi => {
  externalFunction(generatedApi);
});
```

**Comment by konne** [comment]
@marcusoffesson: do you mean that?
export const exposeAppApi = {
    types: "GenericObject",
    init: function init(properties: any) {
        console.log("properties", properties);
      properties.api.app = properties.api.session.getObjectApi({
        handle: 1,
        id: "Doc",
        type: "Doc",
        customType: "Doc",
        delta: true
      });
    }
  };

**Comment by marcusoffesson** [comment]
Hi @konne!

Sorry for this late response. Yes, like your example, but preferably without using the internal `getObjectApi`.

**Comment by konne** [comment]
@thomashaenig please make an offer with override of all Create / CreateGeneric / Open,.. functions on Doc & API and add the app

**Comment by peol** [comment]
Tracked in #220 , we'll re-open these issues once we can work on them.
