### ISSUE TITLE
Packaged mixin: Generic object state

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#275]
### Description

The purpose behind this one is to return locally cached content based on the invalid/valid state given to us from QIX Engine. This reduces bandwidth _a lot_ in larger web application, which in turn also means lower latency/better performance overall. Example:

```js
api.on('changed', () => {
  // state is invalid in QIX Engine, allow fetching remote data:
  api.getLayout().then(layout => {
    // state is now valid, calling `api.getLayout()` will return a locally
    // cached layout until the next `changed` event
  });
});
```

**Comment by konne** [comment]
usally we handle this direct in our code, an in my eyes if coders use getLayout multiple times, even if the engine doesn't change this is bad code style. But now my real question:
What functions do you think are important for that?
getProperties?
.... more?
please add in your code sample api.emit('changed') to make it a good sample.

**Comment by peol** [comment]
Tracked in #220 , we'll re-open these issues once we can work on them.
