### ISSUE TITLE
Add possibility to access schema version from mixins

### ISSUE THREAD

**Issue by konne** [qlik-oss/enigma.js#305]
Like #304 it would be great to get the Version of the loaded shema file to make
it possible to have on mixin that delivers for different shema versions different extensions / overrrides back.

**Comment by marcusoffesson** [comment]
Agree, we should add a `version` property to the schema.

**Comment by konne** [comment]
before an PR can help, it would be great to discuss there this "version" flag is available.
What is your idea?

**Comment by marcusoffesson** [comment]
A simple `version` property on the top level would do (i.e. in parallel to `structs` and `enums`). Sounds good?
