### ISSUE TITLE
object.rangeSelectHyperCubeValues not selecting range

### ISSUE THREAD

**Issue by cookiejest** [qlik-oss/enigma.js#363]
### Description

I am trying to use object.rangeSelectHyperCubeValues. However it does not seem to actually make a selection on the range. Here is the enigma.js promises:

                    .then(() => object.rangeSelectHyperCubeValues('/qHyperCubeDef',
                        [{
                            "qRange": {
                                "qMin": 160,
                                "qMax": 425
                            },
                            "qMeasureIx": 0
                        }]))
                    // Get layout and view the selected values
                    .then(() => { return object.getLayout() })
                    .then((layout) => console.log('THE OUTPUT', layout.qHyperCube.qDataPages[0].qMatrix)))

It just returns the full hypercube with no range selection made.

##### Expected behavior

I am expecting it to filter the rows to where the first measure is between 160 and 425

##### Actual behavior

It returns the full hypercube with no range select

### Environment
windows
qlik sense desktop
##### Library
```
enigma.js 12.20.0 schema
```
##### Operating system
```
[ x] Windows

##### Qlik Sense
```
[ x] Desktop
[ ] Enterprise
```
### Versions

* Node.js: 8.9.3
* Browser: not using browser
* Qlik Sense: 3.2 SR4

**Comment by cookiejest** [comment]
im doing this is node.js whats the best way to view the websocket traffic?

**Comment by peol** [comment]
You may use the traffic:* event(s). https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#event-traffic

**Comment by cookiejest** [comment]
sent { delta: true,
  handle: 2,
  method: 'RangeSelectHyperCubeValues',
  params: [ '/qHyperCubeDef', [ [Object] ] ],
  id: 4,
  jsonrpc: '2.0' }
received { jsonrpc: '2.0',
  id: 4,
  delta: true,
  result: { qSuccess: [ [Object] ] } }

**Comment by cookiejest** [comment]
any ideas?

**Comment by cookiejest** [comment]
it seems it works for a while and then stops working.
