### ISSUE TITLE
Different path on server?

### ISSUE THREAD

**Issue by MartinNorman** [qlik-oss/enigma.js#375]
### Description
Hello,
I have managed to create a solution on my computer that uses enigma to extract data from a Sense app.
But when I try to run the same piece of code on a server where Sense is installed it seems it does not connect to Sense.

Here is the code I'm using:

const enigma = require('enigma.js');
const WebSocket = require('ws');
const serializeapp = require('serializeapp');
const schema = require('enigma.js/schemas/12.20.0.json');
var fs = require('fs');

const session = enigma.create({
	schema,
	url: 'ws://localhost:9076/app/engineData',
	createSocket: url => new WebSocket(url)
});

session.open()
	.then(function(global) {
	global.getDocList().then(function(docList) {
	session.close();
	for (i = 0; i < docList.length; i++) {
		var AppName = docList[i].qDocName;	
		getdata(AppName);
		}
	}, function(err) { console.log('5')});
}, function(err) { console.log('It seems Sense is not responding')});

Could it be that the URL is different on a server compared to the desktop version of Sense?
If so how does one figure out the url to the server version?

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

I expected a list of the apps on the hub

##### Actual behavior

I get the message 'It seems Sense is not responding'

### Environment
Sense server

##### Library
```
[ X] Node.js
[ ] Browser
```
##### Operating system
```
[ X] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[ X] Enterprise
```
### Versions

* Node.js: 8.1.2
* Browser: Chrome
* Qlik Sense:  Nov 2017 release
* Operating system:  Win Server 2016
* [Other relevant versions]

**Comment by peol** [comment]
Hi @MartinNorman, Sense Enterprise is indeed different. By default, it uses secure websocket (wss), so in your case it would be `wss://localhost/app/engineData` (wss defaults to port `443`, just like https). On top of that, you would need to authenticate as a user in Enterprise, you may want to look at one of the authentication examples here: https://github.com/qlik-oss/enigma.js/tree/master/examples#runnable-examples
