### ISSUE TITLE
Websocket Error: Unable to Route

### ISSUE THREAD

**Issue by MF0414** [qlik-oss/enigma.js#380]
### Description
I am connecting to qliksense server from outside of the machine. I am using JWT authentication and am following the example code to the letter, substituting for hostname, prefix, ect. This is a react project and I am using webpack to build. Enigma returns the list of available apps but returns a 500 error when I try to open the first app. 

The error reads: (Unable to route the &quot;Http&quot; request to the following URL: https://127.0.0.1:3000/eidex-user/app/57d6ae3d-6932-4ea1-a799-2b81d534c285)

The local host url is not the url specified in the script. That url is the url that webpack is hosting the app.

### Steps to Reproduce
The config is set with the jwt and the (non-local) host information.
![image](https://user-images.githubusercontent.com/15214956/36690249-b98281f2-1aff-11e8-97da-64b13c4e0626.png)

Then the open first app method.
![image](https://user-images.githubusercontent.com/15214956/36690303-e27486aa-1aff-11e8-95e5-54da9c4321ac.png)

##### Expected behavior

I expect enigma to open the Qliksense application.

##### Actual behavior

I get the app list but 500 error:  (Unable to route the &quot;Http&quot; request to the following URL: https://127.0.0.1:3000/eidex-user/app/57d6ae3d-6932-4ea1-a799-2b81d534c285) when calling.

##### Library
```
[ ] Node.js
[X] Browser
```
##### Operating system
```
[X ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[X] Enterprise
```
### Versions

* Node.js: 9.5
* Browser: Chrome
* Qlik Sense: 3.2
* Operating system: 10
* [Other relevant versions]

**Comment by peol** [comment]
Hi @MF0414, make sure that you have gotten a session from the QRS call. Browsers does not support the `new WebSocket(url, <additionalOptions>)` signature, you cannot set headers on a websocket in a browser environment so an XHR request needs to set it. Additionally, the second parameter (`<additionalOptions>`) in the browser is a string defining the websocket protocol (you should use default, i.e. no second parameter). Let me know if that sorts your issue.

**Comment by MF0414** [comment]
Thanks for the fast response, I fixed the parameter and the header info is under xhrOptions but unfortunately, I am getting the same message. Is it more typical to use something like node or express to communicate server side than to try to request everything client side via brower?

**Comment by peol** [comment]
I think yours is a pretty common use case. I don't recognize the error you are getting though. Are you trying to open the websocket directly towards the Sense Proxy, or through webpack (just to clarify the URLs you are mentioning)? The websocket should look something like this: `wss://your-hostname/jwt-prefix/app/<guid>`.

**Comment by MF0414** [comment]
The url that websocket is taking as a parameter is public-domain-name-of-qs-server/jwt-prefix/app/id. But for some reason the url mentioned in the websocket error is webpack-build-url/jwt-prefix/app/id.

**Comment by peol** [comment]
Ah OK, I don't know why that would be, sounds like the `hostname` variable might be empty then, or perhaps it's a variable webpack injects, dry hardcoding the URL instead of using `${hostname}`.

**Comment by MF0414** [comment]
Still the same error, I am beginning to think this is a websocket/webpack problem or  a Qlik Sense Server problem.

**Comment by peol** [comment]
Yes, your websocket URL seems wrong but you are correct about `ws`—that module should only be used in a Node.js environment. I'm closing this issue for now but feel free to open up a new one if you find any oddities with enigma.js.

Thanks!

**Comment by MF0414** [comment]
Thanks for the help!
