### ISSUE TITLE
connect to existing session

### ISSUE THREAD

**Issue by thomashaenig** [qlik-oss/enigma.js#395]
### Description
i want to connect to the existing session, on the client. The goal is to see the changes in the Browser, when i make selections.
In .net you can set the flag SESSION_ATTATCHED
Is it possible to set any flag like this in enigma.js
### Steps to Reproduce

const websocket = new ws(url, {
            headers: {
                Cookie: `X-Qlik-Session=${this.cookie}`
            }
        });

        const sessionConfig: enigmaJS.IConfig = {
            schema,
            url: url,
            createSocket: url => websocket
        };

##### Expected behavior

when i make a selection with enigma.js i see the changes in the client 

##### Actual behavior

the connection opens a new session and did not share the session. 

### Environment
qlik sense february 

##### Library
```
Node.js
enigma.js
ws
```
##### Operating system
```
[ ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

[x] Enterprise

### Versions

* Node.js: 8
* Browser: chrom
* Qlik Sense: November

**Comment by axelssonHakan** [comment]
Append a `/identity/<string/GUID/ID>` when you create the ws url to identify a specific session to use.

https://github.com/qlik-oss/enigma.js/blob/2fe4538cdeeb6d2a174cd78cf96906de91bcfce5/docs/api.md#sense-utilities-api

https://github.com/qlik-oss/enigma.js/blob/022ebd7533142744ad230362b3808aabb04da84b/test/integration/suspend-resume.spec.js#L12

**Comment by nicefella** [comment]
Hi,

Although I provide X-Qlik-Session value in the identity parameter like /identity/{SESSION-ID} 
I couldn't manage to attach an existing session using Enigma.js

I am using certificate method in the examples to authenticate my user and createSession like this:

const session = enigma.create({
  schema,
  url: buildConfig(),
  createSocket: url => new WebSocket(url,{
    ca: [readCert('root.pem')],
    key: readCert('client_key.pem'),
    cert: readCert('client.pem'),   
    headers: {
      'X-Qlik-User': 'UserDirectory=ismailby; UserId=administrator',
      'Cookie': 'X-Qlik-Session=498b74c9-2261-459e-a4f5-e4cc4ec18b3c'  // this is my X-Qlik-Session value as seen in Chrome Web Tools
    },
  }),
});

function buildConfig()
{
    var newConfig = {
        host: engineHost,
        port: enginePort, // 443
        appId: 'e1ae55a0-e9eb-4556-a466-bd15977a1e9d',
        identity: '498b74c9-2261-459e-a4f5-e4cc4ec18b3c',
        ttl: 300
    }
    return SenseUtilities.buildUrl(newConfig);
}


This is my generated url ::
wss://ismailby/app/e1ae55a0-e9eb-4556-a466-bd15977a1e9d/identity/498b74c9-2261-459e-a4f5-e4cc4ec18b3c/ttl/300

I trace traffic* and I can see SESSION_ATTACHED message but when I make a selection in enigma.js , I can't see the same selection in the app opened in my browser.

Do you think if I miss something?
