### ISSUE TITLE
Example / Documentation for Cancel Request

### ISSUE THREAD

**Issue by konne** [qlik-oss/enigma.js#413]
The engine allows to cancel / abort a request.
Please give a hint / example how this works.

**Comment by peol** [comment]
To clarify:

This example is about documenting and showing how to use the `promise.requestId`, e.g.:

```js
const global = await session.open();
const openDoc = global.openDoc('foo.qvf');
const abortResult = await global.cancelRequest(openDoc.requestId);
console.log(abortResult);
```

**Comment by konne** [comment]
thanks for the example I let this open, because this needs to be documented
I try to find somebody in my team that make a docu PR
