### ISSUE TITLE
Opening multiple applications through different websockets with the same user session

### ISSUE THREAD

**Issue by maximesoulard** [qlik-oss/enigma.js#424]
### Description

I would like to be able to connect to Qlik sense engine API to list applications for a given user, then open all these applications one by one to fetch data (sheets) from them. Until now, the websocket connection is rejected after the 5th session opening.

### Steps to Reproduce

Here is the code I'm using based on enigma-js examples :

```javascript
// Get all applications
const applications = await this.fetchApplications(userName);
// Fetching sheets sequentially
for (const application of applications) {
  application.sheets = await this.fetchSheets(userName, application.qDocId);
}
return applications;
```

```javascript
async function fetchApplications(userName) {
 // Open a new session
  const {global, session} = await this.openSession(userName);
  // Get list of applications
  const applications = await (<any>global).getDocList();
  // Then close session
  await this.closeSession(session);
  return applications;
}

async function openSession(userName, applicationId) {
  const signedToken = this.createToken(userName);
  // If no applicationId, url to Qlik engine API is /engineData
  const qlikConnectionUrl = `${environment.get().qlikSense}/${applicationId || 'engineData'}`;
  const config = {
      schema,
      url: qlikConnectionUrl ,
      createSocket: url => new WebSocket(url, {
        headers: { Authorization: `Bearer ${signedToken}` },
      }, {rejectUnauthorized: false}),
    };
  const session = enigma.create(config);
  const global = await session.open();
  return { session, global };
}

async function fetchSheets(userName, applicationId) {
  const {global, session} = await this.openSession(userName, applicationId);
  const sheets = await this.getSheetsFromDocId(global, applicationId);
  await this.closeSession(session);
  return sheets;
}
```

I've read that even if I close session each time, the user session on Qlik Sense side stays alive until a configured timeout. I guess what I should do is using the same Qlik sense session but opening different websockets : One for fetching the list of applications and then one by application to fetch their sheets.
I've read that issue : https://github.com/qlik-oss/enigma.js/issues/395. Can it help to solve my problem ? If so, how can I get the session ID just opened ?
I tried two things without success :
- With /identity/${userNameFromLdap} but it keeps creating new sessions (logged with `session.on('notification:OnConnected', (data) => console.log(data))`).
- With /ttl/0, it was a naive test to see if it can kill my user session right after websocket is closed.

##### Expected behavior

Opening multiple websockets for different applications sequentially or concurrently.

##### Actual behavior

Getting error "socket closed" after 5 sessions opened.

##### Library
```
[X] Node.js
[ ] Browser
```
##### Operating system
```
[ ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[X] Enterprise
```
### Versions

* Node.js: 8
* Browser: 
* Qlik Sense: September 2017
* Operating system: 
* Enigma : 2.2.1

**Comment by axelssonHakan** [comment]
There is a 5 session limit (by design) in the proxy. You could try running it directly against the QIX engine. Please see https://community.qlik.com/thread/248056

**Comment by maximesoulard** [comment]
The title can be misleading about my problem so I edited it. It's ok for my use case to connect to each application sequentially. 
Also, is there an example of using enigma js to connect directly to the QIX engine ?

**Comment by peol** [comment]
@maximesoulard There is, we have two different examples for Sense Enterprise (under authentication): Here's one using certificates: https://github.com/qlik-oss/enigma.js/tree/master/examples/authentication/sense-using-certificates#readme

**Comment by maximesoulard** [comment]
@peol Thanks for your help, it works as intended. Using only certificates without using the virtual proxy I can now open multiple websocket concurrently.
