### ISSUE TITLE
npm install enigma.js does not include 3.2 schema.json file

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/enigma.js#43]
### Description

enigma.js from npm is 1.0.1.  This version does not appear to include the 3.2 schema
### Steps to Reproduce

1. npm install enigma.js
2. Review the schemas in node_modules/enigma.js/qix folder and see no 3.2 schema.

##### Expected behavior

the 3.2 schema to be there.
##### Actual behavior

the 3.2 schema is missing

[What actually happened]

### Environment
Visual Studio Code

##### Library

* [X] Node.js
* [ ] Browser

##### Operating system

* [X] Windows
* [ ] OSX
* [ ] Linux

##### Qlik Sense

* [ ] Desktop
* [X] Enterprise

**Comment by peol** [comment]
Hi!

It's already on master (see commit https://github.com/qlik-oss/enigma.js/commit/cdd5dc5e05477f2ea200c538cb77ff5b1f329263), we're finishing up a few last issues before we'll release 1.1.0: https://github.com/qlik-oss/enigma.js/milestone/1 :)
