### ISSUE TITLE
simplify authentication scheme when using enigma from browser

### ISSUE THREAD

**Issue by pouc** [qlik-oss/enigma.js#435]
### Description

enigma.js "OnAuthenticationInformation" event loginUri field value is calculated based on the "Origin" header field but it should be calculated based on Request URL in order to be able to handle cases where the page including enigma is not hosted behind the Qlik Sense proxy.

### Steps to Reproduce

1. Design a web page including enigma and host it for instance behind the http-server npm package on port 8080
2. Open an unsecured enigma.js session on localhost port 80 (this requires appropriate CORS headers in Qlik Sense VP Config)

##### Expected behavior

I should get a "must authenticate" event on "localhost:80" with a target id that redirects me to my origin (localhost:8080) AFTER setting a cookie

##### Actual behavior

If your browser does not have a valid cookie for Qlik Sense you will get a "must authenticate" event with a loginUri on the wrong server :

![2018-05-30 15_32_40-loginuri seems wrong issue 435 qlik-oss_enigma js](https://user-images.githubusercontent.com/4351056/40723261-c2ad04f6-641e-11e8-8e08-c1836a7343c5.png)

http://localhost:8080/internal_windows_authentication/?targetId=deec3375-cf7c-4ad1-af7e-52f5f87a0a76

If you modify this url to match the right Qlik Sense host :

http://localhost:80/internal_windows_authentication/?targetId=deec3375-cf7c-4ad1-af7e-52f5f87a0a76

then you get redirected to the following URL :

ws://localhost:8080/app/engineData?qlikTicket=OZYh9eUf2-axBpcB

which fails of course.

If you have a valid cookie, the logout URI seems wrong as well as it targets origin host instead of Qlik Sense host

![enigma](https://user-images.githubusercontent.com/4351056/40722555-ee22c078-641c-11e8-9350-c6e2276bcd47.png)

### Current workaround

Current way to solve this issue is to ignore loginUri and to force this from config for instance, and to use a special mashup deployed behind the proxy to bounce back when authenticated :

```javascript
session.on('traffic:received', (data) => {
  if (data.method === 'OnAuthenticationInformation' && data.params.mustAuthenticate === true) {
    const redirectUrl = window.location.href
    const bounceUrl = `http://localhost/extensions/bounce/bounce.html?bounceUrl=${redirectUrl}`
    window.location.href = bounceUrl
  }
})
```

The link to the mashup :

https://github.com/pouc/qlik-mashup-bounce
 
### Environment

Qlik Sense April 2018 is hosted behind a VMWare NAT network with port 80 & 443 opened accessible on http://localhost/hub

##### Library
```
[ ] Node.js
[x] Browser
```
##### Operating system
```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[x] Enterprise
```
### Versions

* Browser: Chrome 66.0.3359.181
* Qlik Sense: April 2018
* Operating system: Windows 10

**Comment by peol** [comment]
Hi! Sorry for the late response.

This is the default behavior of the Qlik Sense Enterprise Proxy service, not enigma.js itself. If you feel like there should be changes to this behavior, I suggest you file a bug through the support channels.

Thanks for the detailed issue, if every issue was this detailed we'd be in heaven :)

**Comment by countnazgul** [comment]
@peol Any idea if someone reported/escalated this with the support already?

**Comment by peol** [comment]
@countnazgul No, I did a rudimentary search just now and could not find any reported issues.
