### ISSUE TITLE
no folder called 3.2 under schemas->qix folder 

### ISSUE THREAD

**Issue by zuruprem** [qlik-oss/enigma.js#45]
### Description
I have run "npm install --save enigma.js" today to install enigma and then tried to follow your example mentioned in https://github.com/qlik-oss/enigma.js/blob/master/docs/qix/README.md
but faced an error saying there is no 3.2 folder.  Kindly help

**Comment by peol** [comment]
Hi @zuruprem. The documentation reflects what is on the master branch currently, not what is in the latest release of enigma.js. The 3.2 schema of QIX Engine has not been released in a version yet (we're working on it, but if you want to use it, you'd have to build enigma.js yourself). You can find the documentation for the latest release enigma.js here (where it refers you to the 3.1 schema): https://github.com/qlik-oss/enigma.js/tree/v1.0.1/docs

Have a great Sunday!
