### ISSUE TITLE
How Might I use Visualizations?

### ISSUE THREAD

**Issue by momja** [qlik-oss/enigma.js#472]
### Description

Is there a way to make use of the visualizations API with enigma?

### Steps to Reproduce

1.) I created a session App called app
2.) Try to use app.visualization.create()

##### Expected behavior

It would be desirable if this would create a visualization and then return it in a promise like the behavior described [here](https://help.qlik.com/en-US/sense-developer/June2018/Subsystems/APIs/Content/CapabilityAPIs/VisualizationAPI/VisualizationAPI.htm). Maybe I am missusing this, but I think it would be useful to connect to the Visualization API

##### Actual behavior

Returns TypeError: Cannot read property 'create' of undefined

### Environment

VSCode running in Chrome Browser

##### Library
```
[ X] Node.js
[ ] Browser
```
##### Operating system
```
[ X] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ X] Desktop
[ ] Enterprise
```
### Versions

* Node.js: 8.11.3
* Browser: 
* Qlik Sense: April 2018
* Operating system: Windows 7

**Comment by sublibra** [comment]
Closing this issue as works as designed. Please comment and reopen if there is any question.
