### ISSUE TITLE
API Specification which can be consumed in our API governance tools

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/enigma.js#474]
### Description

Create a an API specification which can be used in our API governance tools to follow new, updated and deprecated api calls.

**Comment by wennmo** [comment]
This issue also includes stripping away all jsdoc for private methods that are not part of the api i.e. only the documented api in https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md.

**Comment by hrigner** [comment]
version 2.3.1 released!
