### ISSUE TITLE
Using the engima along with node authentication

### ISSUE THREAD

**Issue by zuruprem** [qlik-oss/enigma.js#48]
### Description
Hi,
First of all, It is a question, not an issue. 
[Description of the question]
Can I use node authentication then further engima snippets mentioned in usage to get the data out of Qlik Sense app as my node programme output?  
[What I am trying to do ]
1. I authenticated the node programme to login to Qlik Sense, since I am not a javascript developer I followed https://www.youtube.com/watch?v=NHa7IvtHV2A and achieved ticketing with Qlik

Perfectly working code is here
[Step1.txt](https://github.com/qlik-oss/enigma.js/files/889635/Step1.txt)

  
2. Now since authentication is happened (at least I assumed). Now added following code to see that my programme has connected to global instance

const enigma = require('enigma.js');
const qixSchema = require('./node_modules/enigma.js/schemas/qix/3.1/schema.json');
const config = {
  schema: qixSchema,
  session: {
      host: 'hosatname' /* original code has real host name */
  }
};
enigma.getService('qix', config).then((qix) => {
  const g = qix.global;
  console.log('Got the global instance');

});

##### Result:

Here I got a result of following error message:
![image](https://cloud.githubusercontent.com/assets/25402337/24604627/33afd262-186e-11e7-9374-2bb8f8c8f5a0.png)

### Versions
* Qlik Sense: QlikSense Enterprise 3.1

Kindly help me. I am ready to provide if you need further details

**Comment by peol** [comment]
Hi!

Please check that you have defined all required configuration parameters (optional column): https://github.com/qlik-oss/enigma.js/blob/v1.0.1/docs/qix/configuration.md

Example in a Node environment: https://github.com/qlik-oss/enigma.js/blob/v1.0.1/docs/qix/configuration.md#example-using-nodejs

It looks like you're missing the `createSocket` function. Let us know if it solves your issue.

**Comment by zuruprem** [comment]
Hi @peol,

thanks for guiding me to right resources to do more with qlik sense.

Currently, I faced an error after running following code in node

**Error:**
![image](https://cloud.githubusercontent.com/assets/25402337/24608892/29d27d9a-1881-11e7-8abc-44c91b3c5ebc.png)

**Code:**
const enigma = require('enigma.js');
const schema = require('C:/Qlik Data Sources/node/node_modules/enigma.js/schemas/qix/3.1/schema.json');
const certificateDir = 'C:/ProgramData/Qlik/Sense/Repository/Exported Certificates/.Local Certificates';
const config = {
  schema: schema,
  appId: 'D1AFF4E6-XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  session: {
    host: 'XXXXX'
  },
  createSocket: (url, sessionConfig) => {
    return new WebSocket(url, {
      ca: [fs.readFileSync(path.resolve(certificateDir, 'root.pem'))],
      key: fs.readFileSync(path.resolve(certificateDir, 'client_key.pem')),
      cert: fs.readFileSync(path.resolve(certificateDir, 'client.pem')),
      headers: {
        'X-Qlik-User': `UserDirectory=${process.env.XXXXXXXXXXXX};UserId=${process.env.XXXXXX}`
      }
    });
  }
};



enigma.getService('qix', config).then((qix) => {
  const g = qix.global;
  console.log('Got the global instance');


});

I found that error started only after second block of code (from enigma.getService() ) placed inside the code.

**Comment by peol** [comment]
As mentioned above the example code, in Node, you'll need to supply a WebSocket implementation yourself :) ``This example opens the same app using the `ws` library (https://github.com/websockets/ws) and it uses the server certificates.``

So you'd need to do `npm install ws` in your terminal, and `const WebSocket = require('ws');` in your file containing the enigma.js configuration.

**Comment by zuruprem** [comment]
I am ashamed to ask you so many questions but I humbly request you to guide me.

I have done that steps mentioned this time error is
![image](https://cloud.githubusercontent.com/assets/25402337/24610031/b9d3669e-1885-11e7-83aa-f3f07690fa88.png)

**Comment by peol** [comment]
The `ReferenceError: fs is not defined` is referring to the `fs.readFileSync` calls made in the `createSocket` in your configuration. `const fs = require('fs')` should solve that.

We're happy to help, but keep in mind that enigma.js in a Node environment is a somewhat advanced topic and require some previous knowledge/experience in general in regards to that environment which we may not be able to provide help with in the future :)

**Comment by zuruprem** [comment]
@peol ,

I will definitely improve my skills, I hope in future I don't ask you same dumb questions :)

Current error is 
![image](https://cloud.githubusercontent.com/assets/25402337/24611016/673fd4ea-1889-11e7-8967-84505871d15d.png)

All of my certificates are in default ".Local certifcates" directory as well as in current node folder in PEM format.

My code is:
[NodeExample.txt](https://github.com/qlik-oss/enigma.js/files/890153/NodeExample.txt)

**Comment by peol** [comment]
That error is likely due to self-signed certificates. I'll try to clarify what's going on.

The example code we have in enigma.js in Node, is referring to when your enigma.js implementation is working towards an Engine instance inside the trusted zone (e.g. not through the Sense proxy).

In your case, from what I can tell, you're trying to consume an Engine through the Sense proxy using a virtual proxy prefix.

In that case you'd likely have to do these additional steps:

* Define the  `session.prefix` configuration option for your virtual proxy prefix: https://github.com/qlik-oss/enigma.js/blob/v1.0.1/docs/qix/configuration.md#config-object

* Disable partial certificate security (since it's self-signed) by setting `rejectUnauthorized: false` in your `createSocket` implementation. E.g.: `createSocket: (url) => new WebSocket(url, { rejectUnauthorized: false })`

**Comment by zuruprem** [comment]
@peol 

May I request you to create an example for me which uses authentication by Sense proxy.  I am trying to follow the List apps example and in the end, some assumption is beating me out. 

Current error:
![image](https://cloud.githubusercontent.com/assets/25402337/24613892/57388e4e-1892-11e7-979b-ebd783b35d6f.png)

Code:
Done the two changes mentioned you updated code is 
[NodeExample.txt](https://github.com/qlik-oss/enigma.js/files/890352/NodeExample.txt)
Also, I should mention that in my environment sense proxy ports are 81 for HTTP and 444 for HTTPS (not the default 80,443)

**Comment by peol** [comment]
I am not able to provide any example at this time, I'm afraid. If you're not using default ports you need to supply it in your configuration, see `session.port`: https://github.com/qlik-oss/enigma.js/blob/v1.0.1/docs/qix/configuration.md#config-object

**Comment by zuruprem** [comment]
@peol, Please maintain the same temper I found the solution working :)
![image](https://cloud.githubusercontent.com/assets/25402337/24614501/121b9534-1894-11e7-8e28-49d14a3ca570.png)

**Comment by zuruprem** [comment]
As you mentioned I have just inputted session.port: 444 and that's done. As you said let me try to read more background concepts.

**Comment by peol** [comment]
Great, happy you got it working!

FYI, we are planning on expanding examples on how to use enigma.js, this is one of them that I'd like for us to provide a more complete example of. Have a great day!

**Comment by RuchitaBK** [comment]
> @peol, Please maintain the same temper I found the solution working :)
> ![image](https://cloud.githubusercontent.com/assets/25402337/24614501/121b9534-1894-11e7-8e28-49d14a3ca570.png)

Hi @zuruprem  can you please provide your updated code ..I am facing same issue from last 10 days .
