### ISSUE TITLE
qix.global.getDocList() is not giving any result

### ISSUE THREAD

**Issue by zuruprem** [qlik-oss/enigma.js#50]
### Description
 I m trying to follow the List Apps example. My programme has connected to engine successfully after that qix.global.getDocList() promise is throwing error

### Steps to Reproduce
I ran the following code.
[NodeExample.txt](https://github.com/qlik-oss/enigma.js/files/899973/NodeExample.txt)

### Error and Output
![image](https://cloud.githubusercontent.com/assets/25402337/24714038/fafab306-1a2f-11e7-9abe-f6e63bf6fe24.png)

Kindly can anyone reconfirm that qix.global.getDocList() is working as mention in List Apps example.

**Comment by peol** [comment]
@zuruprem Could you please give us the output of `console.log(err, err.stack)` instead of your current `console.log`? It may give a hint what's causing the error.

**Comment by zuruprem** [comment]
@peol ,

Where should I give the console.log(err, err.stack) with in the promise or in error catching? I tried this inside the catch function but I got different error related to stack
![image](https://cloud.githubusercontent.com/assets/25402337/24715482/22bb87ae-1a34-11e7-9851-52b786fa7da8.png)

**Comment by peol** [comment]
It looks like Proxy is probably closing your socket instantly. Try binding the notification events:

```js
enigma.getService('qix', {
  listeners: {
    'notification:*': (evt, data) => console.log(evt, data)
  }
});
```

**Comment by zuruprem** [comment]
I did but here is the error
![image](https://cloud.githubusercontent.com/assets/25402337/24717652/e5c874bc-1a3b-11e7-8910-3b3651eb1483.png)

can engima.getService() work with out taking config?

**Comment by peol** [comment]
I meant for you to add the `listeners`-section to your existing configuration :) My bad.

**Comment by zuruprem** [comment]
@peol ,

I am sorry on my poor js skill. I got your point, let me check the  `listeners` and update you.

**Comment by zuruprem** [comment]
@peol,

I failed in logging the error as I am very new to functional programming. However, I can confidently support your argument that that proxy is closing immediately because I am seeing connecting to global instance is perfect and immediate next statement connection an app is failing.

kindly suggest me how can I keep moving towards the objective of getting the list of Apps through node js

**Comment by peol** [comment]
Adding this to your configuration should log any notification proxy might send before closing the socket:

```
'notification:*': function (method, params) {
  console.log('Notification from proxy:', method, params);
}
```

**Comment by zuruprem** [comment]
@peol, Happy Easter

I have done as you instructed still got undefined error.
![image](https://cloud.githubusercontent.com/assets/25402337/25131481/9663b004-244e-11e7-91ec-f38c567d8c46.png)

Attached is the code for your reference
[NodeCode.txt](https://github.com/qlik-oss/enigma.js/files/929580/NodeCode.txt)

**Comment by peol** [comment]
Hi @zuruprem. The `listeners` object should be on the root level in your configuration object, e.g. it should look something like this:

```js
enigma.getService('qix', {
  // generic configuration options
  listeners: {
    // listener options
  },
  session: {
    // session options
  }
});
``` 

See https://github.com/qlik-oss/enigma.js/blob/v1.0.1/docs/qix/configuration.md#config-object

**Comment by zuruprem** [comment]
@peol I have defined `listeners` property in config object only. 

Following is my config object. Kindly suggest if there is anything wrong. Since there is no syntax error I guess defining like this is acceptable

```
const config = {
  schema: schema,
  session: {
    host: 'XXXXXXXXXXX',
	port:444,
	prefix:'/node/',
	listeners: {
  'notification:*': function (method, params) {
    console.log('Notification from proxy:', method, params);
		}
	}
  }
```

**Comment by zuruprem** [comment]
@peol 

Please ignore my last comment, I have defined my config obeject as below. clearlet listens is property for config object only. Still, the code error is same. No listener message is printing the output

```
const config = {
	schema: schema,
/* listeners: {
  'notification:*': function (method, params) {
    console.log('Notification from proxy:', method, params);
  }
}, */
	listeners: {
    'notification:OnSessionClosed': (sessionInfo) => {
      console.log(sessionInfo.message) ;
      
    }
  },
  session: {
    host: 'XXXXXXXXXX',
	port:444,
	prefix:'/node/'
	
  },
  createSocket: (url, sessionConfig) => {
    return new WebSocket(url, {
				rejectUnauthorized: false,
      ca: [fs.readFileSync(path.resolve(certificateDir, 'root.pem'))],
      key: fs.readFileSync(path.resolve(certificateDir, 'client_key.pem')),
      cert: fs.readFileSync(path.resolve(certificateDir, 'client.pem')),
      headers: {
        'X-Qlik-User': `UserDirectory=${process.env.userDirectory};UserId=${process.env.userID}`
      }
    });
  }
};
```

**Comment by zuruprem** [comment]
@peol  Breakthrough!! I got following error
![image](https://cloud.githubusercontent.com/assets/25402337/25144465/8f1ee1c4-2476-11e7-9d29-6d3603518864.png)

**Comment by zuruprem** [comment]
@peol Brakthrouh!! I got following notifition based on code given by you (marked part is server internal name
This notification while creating an app:  
![image](https://cloud.githubusercontent.com/assets/25402337/25144897/1447624e-2478-11e7-85d3-05d6570d3627.png)

Following is error while using getDocList()
![image](https://cloud.githubusercontent.com/assets/25402337/25145020/89822aee-2478-11e7-8ec3-0e6e48908b38.png)

**Comment by peol** [comment]
@zuruprem Great, as noted here: https://help.qlik.com/en-US/sense-developer/3.2/Subsystems/ProxyServiceAPI/Content/ProxyServiceAPI/ProxyServiceAPI-Msgs-Proxy-Clients-OnAuthenticationInformation.htm, if the `mustAuthenticate` flag is true you must navigate to that URL. It may be a misconfigured virtual proxy if you expected to not need an authentication to happen here.
