### ISSUE TITLE
Connect to Qlik server that is outside my network

### ISSUE THREAD

**Issue by jacekmoss** [qlik-oss/enigma.js#507]
### Description

Hi, 

I want to connect to qlik engine API outside my network - I have access to QMC and HUB. When I'm connected to VPN, it's really easy to connect to api using certificates, but how can i connect without VPN? Is that even possible? 

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

##### Library
```
[x ] Node.js
[ ] Browser
```
##### Operating system
```
[ x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[x ] Enterprise
```
### Versions

* Node.js: 
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by peol** [comment]
Hi! If I understand you correctly, you mean that you have access to engine directly (port 4747) when you're on your VPN, but only proxy when not (i.e. https://domain/qmc)?

If so, you would need to implement authentication against the proxy using e.g. JWT, you can find an example of that here: https://github.com/qlik-oss/enigma.js/tree/master/examples/authentication/sense-using-jwt

Does that answer your question?
