### ISSUE TITLE
Error: Global of undefined - QS Extension creating session app

### ISSUE THREAD

**Issue by ClimberExtensions** [qlik-oss/enigma.js#56]
### Description
I'm trying to create a session app with enigma.js in a Qlik Sense extension. But when I call getService('qix',enigmaConfig) I get this error:
![image](https://cloud.githubusercontent.com/assets/20192393/26235341/bebea4a8-3c6a-11e7-8c4b-48314ef8a37e.png)
And if I step in to the code, this is where it happens:
![image](https://cloud.githubusercontent.com/assets/20192393/26235369/f3d684da-3c6a-11e7-96a3-8155aeb72e05.png)

### Steps to Reproduce
enigma = '../.././external/qlik/enigma'
qixSchema = 'text!../.././external/qlik/qix/3.2/schema.json'
'ng!$q' = $q
'qlik' = qlik
app = qlik.currApp();

var enigmaConfig = {
    Promise: $q,
    appId: app.id,
    schema: qixSchema,
    session: {
        host: $window.location.host,
        secure: $window.location.protocol === 'https:'
    }
};
enigma.getService('qix', enigmaConfig).then(function (qix) {
    console.log('qix', qix);
});

### Versions
* Enigma.js: 1.1.1
* Browser: Chrome 58.0.3029.110 (64-bit)
* Qlik Sense: 3.2 SR2
* Operating system: Windows 10

**Comment by marcusoffesson** [comment]
Hi @ClimberExtensions!

It looks like qixSchema is invalid. I notice you load it as text while enigma expect it to be an object structure. Can you see if the config below works?

```js
var enigmaConfig = {
    Promise: $q,
    appId: app.id,
    schema: JSON.parser(qixSchema),
    session: {
        host: $window.location.host,
        secure: $window.location.protocol === 'https:'
    }
};
```

On a side note, if you intend to create a session app, `appId` is not needed (and should not be part of the config).

**Comment by kfsjostrand** [comment]
Thanks for the quick response , that solved the problem!

**Comment by peol** [comment]
Awesome, thanks for responding :) Have a great weekend!
