### ISSUE TITLE
Error: Not Connected

### ISSUE THREAD

**Issue by sakaga** [qlik-oss/enigma.js#562]
### Cannot connect to qlik core engine

 This is just a index.js file. Qlik Engine is already running on my localhost

### Steps to Reproduce
node index.js
```
const WebSocket = require('ws');
const schema = require('enigma.js/schemas/12.20.0.json');
const enigma = require('enigma.js');

//const host = process.argv.slice(2)[0] || 'localhost';
//const port = host === 'localhost' ? 19076 : 9076;

// create a new session:
const session = enigma.create({
  schema,
  url: `http://localhost:19076/app/engineData`,
  createSocket(url) {
    return new WebSocket(url);
  },
});

//console.log(session)

let global;
let app;
let reloadRequestId;
const appId = 'papfizer.qvf';
let connectionId;
const trafficLog = false;

if (trafficLog) {
  // bind traffic events to log what is sent and received on the socket:
  session.on('traffic:sent', data => console.log('sent:', data));
  session.on('traffic:received', data => console.log('received:', data));
}

session
  .open()
  .then((_global) => {
    global = _global;
    console.log('Creating/opening app');
    return global
      .createApp(appId)
      .then(appInfo => global.openDoc(appInfo.qAppId))
      .catch(() => global.openDoc(appId));
  }).then(function(value) {
  console.log(value);
  // expected output: "Success!"
}).catch(function(e){
	console.log("error on the way")
	console.log(e)
    //error handling logic
});;
```

##### Expected behavior

It should connect

##### Actual behavior
Not connected

![image](https://user-images.githubusercontent.com/11698104/51558039-78b35800-1ea4-11e9-9873-2828dddf74a1.png)

##### Operating system
```
[*] Windows
[ ] OSX
[ ] Linux
```

**Comment by sakaga** [comment]
![image](https://user-images.githubusercontent.com/11698104/51558014-6d602c80-1ea4-11e9-99df-358a6731eb26.png)

**Comment by peol** [comment]
Hi, you connect using the websocket protocol (`ws://`), not `http://`. Try `ws://localhost:19076/app/engineData`.

**Comment by sakaga** [comment]
getting same error @peol

**Comment by sakaga** [comment]
when i am doing `console.log(session)`

![image](https://user-images.githubusercontent.com/11698104/51558253-ff683500-1ea4-11e9-9510-7fd6d42b09e8.png)

**Comment by peol** [comment]
Issue was expired engine, starting the latest engine version solved it.
