### ISSUE TITLE
example of using getProgress with doReload

### ISSUE THREAD

**Issue by cookiejest** [qlik-oss/enigma.js#589]
I am struggling to find any example or using getProgress to find out the status of a reload. I know it needs to be passed the requestId but I tried it and no matter what requestId gets passed it always just outputs:

{ qStarted: true,
  qFinished: true,
  qCompleted: 0,
  qTotal: 0,
  qKB: 0,
  qMillisecs: 0,
  qErrorData: [],
  qPersistentProgressMessages: [],
  qTransientProgressMessage: { qMessageCode: 0, qMessageParameters: [ '' ] } }

Any ideas? A simple enigma example would be great.

**Comment by peol** [comment]
Sorry that we missed this issue. You can send in `-1`: `getProgress(-1)`. As for error messages, you can configure how reload works in your session: https://core.qlik.com/services/qix-engine/apis/qix/global/#configurereload
