### ISSUE TITLE
Expose services with better granularity

### ISSUE THREAD

**Issue by nilzona** [qlik-oss/enigma.js#60]
in enigma version 1.1 support for rest services was introduced. That made the package size grow from approximately 70k to 1M.

If I only intend to use the qix services with enigma I would like to do something like:
```
import {qix} from 'enigma.js';
qix.getService(theConfig);
````
And then I would only read the 70k javascript needed for that service.

**Comment by ricsv** [comment]
A suggestion I had would be to opt in on which services to use. Each service would be bundled as a separate module and the user would be responsible of setting them up:

```
import enigma from 'enigma.js';
import qix from 'enigma.js/services/qix';

enigma.use(qix);

qix.getService(theConfig);
```

This way it would be possible to choose which services to include and get a minimal bundle.

The `use` function (which is inspired from Vue) could take the Enigma instance as a parameter to simplify dependencies. Seen from the qix module:

```
module.exports = function register(enigma) {
  enigma.registerService("qix", qixService);
};
```

Seen from Enigma:

```
export function use(registerModule) {
  registerModule(enigma);
}
```

This approach assumes modules will be hosted internally in the Enigma repository and even be a part of the same NPM package. An alternative could also be to put modules in different packages, using them with:

```
import enigma from 'enigma.js';
import qix from 'enigma.js-qix';
/* ... */
```

**Comment by marcusoffesson** [comment]
For enigma v2, we discussed to simply have two modules: `qix` and `rest` which can be included independent of each other.
