### ISSUE TITLE
Simplify/avoid config object

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#64]
Over time, the config object has become bloated and we would like to simplify it in version 2.

Preferably, the "connect"-methods should have a single URL parameter and no config object at all. This might be hard (impossible?) to achieve, given that it should be possible to register listeners, etc. before a connection is established. Ideas and comments are welcome!

**Comment by peol** [comment]
We should also investigate the possibility of having `enigma.create()` synchronous, and allow the use to bind the events they today have to use `config.listeners` for. I imagine something similar to this:

```js
const session = enigma.create({ host: '127.0.0.1', port: 1234 });

session.on('notification:OnAuthenticationInfo', (evt) => console.log(evt));
session.on('traffic:in', (data) => console.log('<-', data));
session.on('traffic:out', (data) => console.log('->', data));

session.getGlobal()
  .then(global => global.openDoc('foo.qvf')
  .then(doc => doc.doReload());

```

**Comment by peol** [comment]
Proposed configuration in 2.0:

```
| Property         | Type     | Optional   | Default   | Description |
|------------------|----------|------------|-----------|-------------|
| `schema`         | Object   | No         |           | Object containing the specification for the Qix API. Originates from an Engine build and is bound to a specific version of Engine. |
| `url`            | String   | No         |           | String containing a proper websocket URL to an Engine.
| `createSocket`   | Function | In browser |           | A function to use when instantiating the WebSocket, mandatory for NodeJS. |
| `mixins`         | Array    | Yes        | `[]`      | Mixins to extend/augment the Engine API (see more on [Using mixins](mixins.md)).
| `delta`          | Boolean  | Yes        | `true`    | If set to `false`, will disable the use of the bandwidth-reducing delta protocol. |
| `suspendOnClose` | Boolean  | Yes        | `false`   | Set to `true` if the session should be suspended instead of closed when websocket is closed. See [Session](session.md) for details. |
| `Promise`        | Promise  | Yes        | `Promise` | ES6-compatible Promise library. |
```

These configuration properties are removed:

* `config.appId`: Removed in favour of #86, #68, #87
* `config.noData`: Removed in favour of #86, #68, #87
* `config.handleLog`: Removed in favour of #81
* `config.listeners`: Removed in favour of #87
* `config.session.*`: Removed in favour of #86

**Comment by mindspank** [comment]
I can understand the reasoning behind removing `config.appId` but it was quite convenient to avoid having to call `openDoc` yourself. Perhaps a middle-ground approach could work, supplying a app id in the config and `connect()` returns both the global handle and the app handle but without making assumptions around urls and how you want to handle your websocket connections.

**Comment by marcusoffesson** [comment]
Hi @mindspank!

You make a good point and I understand the benefit of having the `config.appId` property. On the other hand, the simplicity of the `config` object outweighs convenience of not having to call `openDoc()`.

We are considering to add support for session mixins (not in scope for v2). The `connect()` method could then be overridden to also handle the `openDoc()` call.

**Comment by marcusoffesson** [comment]
Done!

**Comment by mindspank** [comment]
Is it simplifying though? The benefit of having enigma performing the `openDoc` was that it abstracted away the need to learn session sharing and session scoping within QIX.
