### ISSUE TITLE
App.Visualisation: ExportImg & ExportPDF

### ISSUE THREAD

**Issue by ivanshamaev** [qlik-oss/enigma.js#651]
### Hello!
Is there a plan to add a methods for exporting images and pdf to the enigma? Now I can not export image or pdf from my Qlik Sense App. If possible, please give a working example.

**Comment by peol** [comment]
Hi @ivanshamaev! enigma.js is a library purely for the Engine API (websocket). Exporting images/PDFs are REST APIs in Qlik Sense to other services (reporting), and is exposed through the capability API:
* https://help.qlik.com/en-US/sense-developer/September2019/Subsystems/APIs/Content/Sense_ClientAPIs/CapabilityAPIs/VisualizationAPI/exportImg-method.htm
* https://help.qlik.com/en-US/sense-developer/September2019/Subsystems/APIs/Content/Sense_ClientAPIs/CapabilityAPIs/VisualizationAPI/exportPdf-method.htm

**Comment by ivanshamaev** [comment]
@peol Thank you very much for your reply!
