### ISSUE TITLE
QIX service, document request id

### ISSUE THREAD

**Issue by marcusoffesson** [qlik-oss/enigma.js#69]
In order to cancel outstanding requests (QIX method `CancelRequest`), the request id is needed. The client can access the request id as enigma.js adds it to the returned promise but this is highly undocumented! Make sure it's in the v2 docs. 👍

**Comment by peol** [comment]
I think it's a pretty small task to do this, and would likely not change in v2 so perhaps we should just do it? :)

**Comment by marcusoffesson** [comment]
Sure thing! Do we have any releases planned before v2?

**Comment by peol** [comment]
There's a bugfix release planned today :)
