### ISSUE TITLE
How to suspend() & resume() socket connection in engima js with angular2+

### ISSUE THREAD

**Issue by hshahul** [qlik-oss/enigma.js#697]
Hi,

I am using qlik enigma js with angular framework, each components are using each socket connections. I want to restrict the socket connection. 

Could you please help me

**Comment by axelssonHakan** [comment]
If the components uses the same App you should be able to share the session between the components. Not sure in what context you are using enigma.js but maybe the example for QLIK Core could help you.
https://github.com/qlik-oss/core-get-started/tree/master/src/hello-visualization

**Comment by axelssonHakan** [comment]
@hshahul do you have any more input on this issue? Otherwise, we will close this issue.

**Comment by hshahul** [comment]
sorry for late response..

Thanks for you comments and please close this ticket
