### ISSUE TITLE
Undocumented methods included in the QIX schema

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/enigma.js#7]
### Description

There are multiple methods exposed via the schema that are un-documented (and potentially un-supported) according to the official Engine api documentation at help.qlik.com

Two examples would be `ReduceData` and `RemoveAllData` on the Doc class
https://github.com/qlik-oss/enigma.js/blob/master/schemas/qix/3.1/schema.json#L556

I'd propose we either purge them from the schema or make sure we document the methods included in the schema to avoid confusion.

**Comment by axelssonHakan** [comment]
These functions is also exposed in devhub/Engine API Explorer

**Comment by michellefthomas** [comment]
Hi @mindspank and @axelssonHakan: If these methods should be in the Engine API help, could one of you please log a JIRA bug (assuming they are still missing) for the docs team?
