### ISSUE TITLE
User cannot connect to apps via enigma js

### ISSUE THREAD

**Issue by hshahul** [qlik-oss/enigma.js#714]
Hi there,
I was wondering if anyone can help with my issue. A user who develops mashups using enigma js is unable to connect to qlik sense apps. But they can access the Qlik Sense hub and access apps normally. Other users don't have this issue and can connect fine.

In the Google Chrome logs, we can see a request rejected error, so I am guessing this is some authentication issue. Any help would be appreciated.

Thanks,
Sahul

**Comment by axelssonHakan** [comment]
Has the URL there the mashup is running been whitelisted in the QMC?

**Comment by hshahul** [comment]
Yes it has. This issue has appeared for the one user mentioned. Before this, it was working. If another user logs into the affected users machine and executes the same code, they can connect. So this seems to be some kind of authentication issue.
If the user accesses the underlying apps through the hub, there is no issue. It is only happening when connecting through enigma js.

**Comment by axelssonHakan** [comment]
Are you connecting to a Qlik Sense Enterprise through proxy? In that case, you need a valid session cookie to be able to establish a WS connection.
Enigma.js doesn't provide any authentication. This has to be done using other APIs against the Qlik Sense Enterprise. https://help.qlik.com/en-US/sense-developer/February2020/Subsystems/ProxyServiceAPI/Content/Sense_ProxyServiceAPI/ProxyServiceAPI-ProxyServiceAPI-Authentication.htm

**Comment by axelssonHakan** [comment]
Closed due to inactivity
