### ISSUE TITLE
Master dimension/measure popup missing

### ISSUE THREAD

**Issue by 4kuato** [qlik-oss/enigma.js#715]
### Description

Hi, a popup window shows up when I click on a master dimension (or measure) manually created, however, it's missing when I create the object using "createDimension".

### Steps to Reproduce

1. Connect to qlik server: session.open().

2. global.openDoc(<app_id>).

3. doc.createDimension(qProp) with

qProp = {
        "qInfo": {
          "qId": <id>,
          "qType": "dimension"
        },
        "qDim": {
          "title": <title>,
          "qGrouping": "N",
          "qFieldDefs": [
            <def>
          ],
          "qFieldLabels": [
            <label>
          ]
        },
        "qMetaDef": {
          "title": <title>
        }
    }

4. doc.saveObjects()

##### Expected behavior

Popup in both objects.

##### Actual behavior

![imagen](https://user-images.githubusercontent.com/1623421/75997007-02828100-5eff-11ea-9e86-c0655d080867.png)

![imagen](https://user-images.githubusercontent.com/1623421/75997812-30b49080-5f00-11ea-8fa8-8a5f77c27bf6.png)

##### Library
```
[x] Node.js
[] Browser
```
##### Operating system
```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[x] Enterprise
```
### Versions

* Node.js: 12.6.1
* Browser: Firefox & Chrome
* Qlik Sense: 13.51.6
* Operating system: Windows 10
* [Other relevant versions]

**Comment by sublibra** [comment]
Thank you for filing an issue. 

The behaviour in the Qlik Sense Client is based on which properties are set to the dimension object and thus not related to the enigma.js repository.

The required properties is described by the Qlik Sense client but public. If you would like to find out what properties are used in existing objects you could either retrieve them programmatically or use the [corectl](https://github.com/qlik-oss/corectl) tool to retrieve the object. 

In this particular case, you are missing an `tag` property in `qMetaDef`. Example

```json
"qMetaDef": {
      "title": "A title",
      "tags": []
    }
```

**Comment by 4kuato** [comment]
Thanks sublibra!
