### ISSUE TITLE
Error: "app.getFieldAndColumnSamples is not a function"

### ISSUE THREAD

**Issue by huriferencnextent** [qlik-oss/enigma.js#720]
### Description
Hi there,
I want to run GetFieldAndColumnSamples function on my Node.js app, but it's not working.

### Steps to Reproduce
1. Connect to qlik server:
const global = await session.open();
2. Open doc:
const app = await global.openDoc(appId);
3. Get field and column samples:
const fieldAndColumns = await app.getFieldAndColumnSamples(<field>);

##### Expected behavior
fieldAndColumns variable with data.

##### Actual behavior
"app.getFieldAndColumnSamples is not a function"

##### Library
```
[x] Node.js
[ ] Browser
```
##### Operating system
```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[x] Desktop
[ ] Enterprise
```
### Versions

* Node.js: 12.13.0
* Qlik Sense: 13.32.2
* Operating system: Windows 10
* [Other relevant versions]

**Comment by axelssonHakan** [comment]
It seems that the published schemas doesn't have that "new" method.
We are working on publishing a new schema version

**Comment by huriferencnextent** [comment]
Okay, thank you :)

**Comment by axelssonHakan** [comment]
Please verify that the latest version solves your issue

BR Håkan

**Comment by huriferencnextent** [comment]
Hi, it's working very well. Thanks :)

**Comment by axelssonHakan** [comment]
Great 👍
