### ISSUE TITLE
There is no documentation available for connecting to QS engine via virtual proxy configured as ticketing

### ISSUE THREAD

**Issue by kashanmemon** [qlik-oss/enigma.js#745]
I am working on a specification where a virtual proxy is configured as ticketing. I have to use this virtual proxy to connect to QS engine but I haven't found any doc about this. I have found a documentation for JWT virtual proxy but not for ticket. Please provide any example for this use case?

**Comment by axelssonHakan** [comment]
**enigma.js** is a lib for communicating with the QIX Engine and doesn't handle the login/ticketing that is done against the Qlik Sense Enterprise Proxy. 

We would like to make an example but it hasn't been prioritized yet.

There are other libs that could help you with the ticketing - have a look at https://github.com/braathen/qlik-auth
