### ISSUE TITLE
How to do authentication with enigma in browser

### ISSUE THREAD

**Issue by sshelake25** [qlik-oss/enigma.js#760]
### Description

I have angular application. i want to connect to qlik sense sever by enigma js.
I did a node standalone example working with JWT token. but when i am integrating that example with angular application as browser Websoket connection does not allow to send header as part of the connection. how I can do authentication in the browser with the angular application.

Could you suggest any possible ways to authenticate in browser base application with enigma js

**Comment by sublibra** [comment]
Hello,

We have an example in this repo:
https://github.com/qlik-oss/enigma.js/tree/master/examples/complete/car-models
which seems to resemble your case. If Sense proxy requires a login you need to direct the user to the login-URL in the Sense proxy message.

Please take a look and come back if you have more questions.
