### ISSUE TITLE
Default port incorrectly documented

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/enigma.js#8]
### Description
The docs states that `session.port` should default to `4747` however it does not.

### Steps to Reproduce

```
const enigma = require('enigma.js');
const qixSchema = require('../node_modules/enigma.js/schemas/qix/3.1/schema.json');
const WebSocket = require('ws');

const config = {
    schema: qixSchema,
    session: {
        unsecure: true
    },
    createSocket: (url) => {
        console.log(url)
        return new WebSocket(url)
    }
};

enigma.getService('qix', config).catch(err => console.log(err))
```

##### Expected behavior
I expected the port to default to 4747

##### Actual behavior

It omits port completely 

##### Library

* [x] Node.js
* [ ] Browser

##### Operating system

* [x] Windows
* [ ] OSX
* [ ] Linux

##### Qlik Sense

* [x] Desktop
* [ ] Enterprise

### Versions

* Node.js: 6.7.0
* Browser: Chrome
* Qlik Sense: 3.1 SR3
* Operating system: Windows

**Comment by mindspank** [comment]
This is the part of the documentation for `session.port` https://github.com/qlik-oss/enigma.js/blob/master/docs/qix/configuration.md#config-object

**Comment by peol** [comment]
Yes, the documentation needs updating (as well a couple of examples). It was decided a while back that we should default to the Enterprise configuration (and Proxy as entrypoint).
