### ISSUE TITLE
Qlik Saas blocking websocket connections from origins not the tenant 

### ISSUE THREAD

**Issue by mattkizaric-leveragelab** [qlik-oss/enigma.js#856]
### Description

Hello,

I know enigma does not technically deal with authentication; however I was looking for some guidance on weird behavior that I have been experiencing while trying to use the library. All websocket connections fail unless the origin is our qlik saas tenant. 

When running our SPA in development (localhost:5000) i have verified that I have the correct cookies and my qlik web integration id token are set correctly.

![Screen Shot 2021-03-12 at 10 32 18 PM](https://user-images.githubusercontent.com/73000879/111019194-44040280-8383-11eb-9545-88de96e69b39.png)
![Screen Shot 2021-03-12 at 10 33 13 PM](https://user-images.githubusercontent.com/73000879/111019203-55e5a580-8383-11eb-886d-1d79197d7751.png)

However creating a new websocket connection keeps failing:
<img width="618" alt="Screen Shot 2021-03-12 at 10 39 33 PM" src="https://user-images.githubusercontent.com/73000879/111019314-02c02280-8384-11eb-952f-8d71b518e1d3.png">

When I try the very same configuration in the browser while in my qlik tenant, it works though:
<img width="590" alt="Screen Shot 2021-03-12 at 10 42 38 PM" src="https://user-images.githubusercontent.com/73000879/111019390-8974ff80-8384-11eb-9ed2-5b57b09390b1.png">

 Do we need to whitelist origins for the websocket to connect to? I have also replicated this in our dev environment incase it was a http vs https problem.

### Steps to Reproduce

1. Attempt to create a connection following the steps in [this](https://qlik.dev/tutorials/build-a-simple-web-app) tutorial. Fails
2. Attempt to use the same websocket url connection in a browser at the qlik saas tenant. Succeeds

##### Expected behavior

Creation of enigma session (Websocket) should not fail.

##### Actual behavior

Creation of the underlying websocket only works when the origin in the request is the qlik saas tenant

##### Library
```
[ ] Node.js
[ X ] Browser
```
##### Operating system
```
[ ] Windows
[ X ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[X] Enterprise
```
### Versions

* Node.js: 
* Browser: Chrome: 89.0.4389.82
* Qlik Sense: ?
* Operating system: macOS Catalina 10.15.7
* [Other relevant versions]

**Comment by axelssonHakan** [comment]
Hi

Sorry for the late answer. I have tried the linked tutorial, and I'm able to connect to a QCS app after adding the `host` to web-integration (in my case `https://127.0.0.1:8080`)

Do you have any example code you can share?
What kind of devServer are you using?

**Comment by mattkizaric-leveragelab** [comment]
@axelssonHakan We are using firebase's hosting emulator for local development. As for our frontend web framework, we are using React. Our team has been able to log in successfully with qlik as shown above, however even when we whitelist our dev domain for the web-integration we are unable to connect via websockets to our qlik domain.

In Chrome Console:
```js
const webIntegrationId = ""
const csrfToken = ""
const appId = ""
const tenantUri = ""
let wsurl = `${tenantUri.replace(
      'https',
      'wss'
    )}app/${appId}?qlik-web-integration-id=${webIntegrationId}&qlik-csrf-token=${csrfToken}`
new WebSocket(wsurl);
```
It's my understanding that similar code is called by enigma [here](https://github.com/qlik-oss/enigma.js/blob/master/src/rpc.js#L40). I have verified that calling the enigma library leads to the same result as the above code. 

Could you see if the above snippit works for you in the developer console? We have a temporary solution right now with embedded sheets, so I was able to verify that this worked in the domain context of our qlik saas tenant.

**Comment by axelssonHakan** [comment]
I just installed the hosting emulator and it seems fine to "integrate" the tutorial you mentioned.
<img width="1865" alt="Screenshot 2021-03-25 at 09 32 51" src="https://user-images.githubusercontent.com/5768580/112443358-25bbe080-8d4d-11eb-92c3-0971c64e90de.png">

I'm using the config from the tutorial:
```
  try {
    // fetch the CSRF token:
    const res = await request('/api/v1/csrf-token', false);
    const csrfToken = res.headers.get('qlik-csrf-token');

    // fetch the list of available apps:
    const apps = await request('/api/v1/items?resourceType=app');

    if (!apps.data.length) {
      titleElement.innerHTML = 'No apps available';
      return;
    }

    // grab the first app id in the list:
    const appId = apps.data[0].resourceId;

    // build a websocket URL:
    const url = `${tenantUri.replace(
      'https',
      'wss'
    )}/app/${appId}?qlik-web-integration-id=${webIntegrationId}&qlik-csrf-token=${csrfToken}`;

    // fetch the engine API schema:
    const schema = await (
      await fetch('https://unpkg.com/enigma.js@2.7.0/schemas/12.612.0.json')
    ).json();

    // create the enigma.js session:
    const session = window.enigma.create({ url, schema });
    const global = await session.open();

    // open the app, and fetch the layout:
    const app = await global.openDoc(appId);
    const appLayout = await app.getAppLayout();

    // finally, present the app title in your web app:
    titleElement.innerHTML = appLayout.qTitle;
  } catch (err) {
    window.console.log('Error while setting up:', err);
  }
```

**Comment by mattkizaric-leveragelab** [comment]
@axelssonHakan Hmmm I'll test this over the weekend and post my findings. What version of chrome are you on? I know with recent updates with cookies, we have issues with incognito browsers not authenticating end users. Our whitelabed solution is using JWT authentication and maybe the qlik cookies are not being passed with the request.

**Comment by mattkizaric-leveragelab** [comment]
@axelssonHakan I went back and did the tutorial again. My issue was as a tenant admin I am able to see all apps across spaces, but I was not explicitly added to the space of the app i wanted to connect to. Interestingly, I am able to embed an iframe and calling the Qlik api while in our Saas UI via the browser console worked fine regardless of my space access. That does not seem to be related to enigma, but I appreciate your timely responses. Closing this issue.

**Comment by axelssonHakan** [comment]
Thanks for responding with updated status

**Comment by jeff-1984** [comment]
Hello, after the upgrade of Qlik Sense November 2024, we had some issues with an extension that was using enigma.js

The explanation here is not sufficient, it could help only in nodejs context : https://community.qlik.com/t5/Support-Updates/Upgrade-advisory-for-Qlik-Sense-on-premise-November-2024/bc-p/2488274

I had to debug the enigma.js code to find how to pass the csrf-token correctly when calling engigma.getService('qix, config)... This could maybe help other people : 

`
      const getCsrfToken = () => {
          return fetch(`/qps/csrftoken`, {
            method: 'GET',
            credentials: 'include'
          });
        };

        getCsrfToken()
        .then(res => {
          const csrfToken = res.headers.get('qlik-csrf-token');         
          const enigmaConfig = {
            Promise: $q,
            appId: $scope.app.id,
            schema: JSON.parse(qixSchema),
            session: {
              host: $window.location.host,
              secure: $window.location.protocol === 'https:',
              urlParams: {
                "qlik-csrf-token": csrfToken
              }
            }
          };

          enigma.getService('qix', enigmaConfig)
            .then(function(qix) {
              // you can use qix from here !

            })
            .catch(function(err) {
              console.log('error : ' + err);
            });
          });
        }
`

**Comment by uritomas** [comment]
@jeff-1984, same problem here after updating QS November 2024. I've found a similar solution getting the csrf token this way. The only difference is we are using enigma.create() and it start working properly until I tried  to open two qlik applications sinultaneously.
Did your solution allow you to open more than an app?

Thanks
