### ISSUE TITLE
No clear documentation on how to authenticate

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#89]
It would be nice if you can make a default flowchart and example code on how to authenticate for the most common scenarios. Example image:
![image](https://user-images.githubusercontent.com/12411165/27590661-aecf5cd2-5b4f-11e7-8eb2-3a33b743bd71.png)

Step to [authenticate](https://github.com/qlik-oss/enigma.js/blob/master/docs/authentication.md)  (if you use ticketing)
1. Fetch a ticket
2. Consume the ticket.  You consume a ticket by issuing a http get to a proxy resource with `qlikTicket=<value>` attached to the url. You can supply the ticket in the session.urlParams object.
3. You are authenticated, do whatever you want

```
{
  session: {
    urlParams: {
      qlikTicket: 'poop'
    }
  }
}
```
[slack message](https://qlik-branch.slack.com/archives/C3FKGA7UZ/p1497375509029312)

**Comment by peol** [comment]
Hi @QHose. Except for the flow chart, what would be missing from https://github.com/qlik-oss/enigma.js/blob/v1.x/docs/authentication.md ? Do you want to see complete examples of how to use it in Sense? We try to keep enigma.js somewhat independent from e.g. Sense, but I'm sure such documentation would be nice to have _somewhere_ (either in the Sense Help [there are related documentation in there already in how authentication works in that context], or as a sense example in `examples/` perhaps). enigma.js generally comes in _after_ authentication should have been completed, so it's a fine line to balance when it comes to examples here.

Interested to hear your thoughts!

**Comment by QHose** [comment]
Hi,

I just updated my initial question. So lets tell a story on what my learning curve was:

1. I know I need a session cookie somehow
2. It would be nice if the docs tell how to get authenticated before you can make your call. 
3. So I know how to get a ticket (we can add a link to the Qlik help, request ticket)
4. But where to put it? 

It would be nice to see example code on where to put the ticket. Also nowhere is explained what the purpose of the OnAuthenticationInformation is. So in general I would like to see more end to end examples for common tasks. (another example: how to sort a hypercube? where can I find how to do this?)

**Comment by peol** [comment]
Hi, I agree that the auth docs probably should cover ticketing in Sense Enterprise as well.

Under the configuration documenation (https://github.com/qlik-oss/enigma.js/blob/v1.x/docs/qix/configuration.md) there are a few things to notice:

* `createSocket` hints towards websockets using URLs (albeit we don't explicitly talk about what websockets are)

* The deprecated `reloadUri` points you towards `urlParams`, which is a generic way of adding query parameters to the websocket URL (including `ticket` and `reloadUri`)

> Also nowhere is explained what the purpose of the OnAuthenticationInformation is

I think https://github.com/qlik-oss/enigma.js/blob/v1.x/docs/authentication.md#browser is pretty clear (there's even a link to Sense help explaining what it is), what is missing here?

> So in general I would like to see more end to end examples for common tasks.

Yeah, that's a good idea. We have been talking about creating more examples, we'll keep the hypercube sorting in mind.

Disclaimer
We are working towards a new major enigma.js version, and the configuration and entry API will be quite different but hopefully clearer, so we will likely not add any more examples until we are closer to being done with that work. You can track it here: https://github.com/qlik-oss/enigma.js/milestone/2

And the configuration/API proposal:

Configuration: https://github.com/qlik-oss/enigma.js/issues/64#issuecomment-311322205
API: https://github.com/qlik-oss/enigma.js/issues/87

**Comment by marcusoffesson** [comment]
See [Authentication: Qlik Sense JSON Web Token](https://github.com/qlik-oss/enigma.js/tree/master/examples/authentication/sense-using-jwt)
