### ISSUE TITLE
Property 'openDoc' does not exist on type 'IGeneratedAPI

### ISSUE THREAD

**Issue by LiKang6688** [qlik-oss/enigma.js#954]
### Description

[Description of the issue]

Following the code snippet from https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#sessionopen

```
session.open().then((global) => {
  global.openDoc('my-document.qvf');
});

```
Property 'opendoc' does not exist on type 'IGeneratedAPI'

### Environment
Developing a mashup in typescript
<img width="929" alt="Screenshot 2022-06-23 at 02 34 07" src="https://user-images.githubusercontent.com/4471489/175182882-3efb4582-f8d4-4ac9-8e8f-56d163e9ffce.png">

##### Library
```
[ ] Node.js
[ ] Browser
```
##### Operating system
```
[ ] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[ ] Enterprise
```
### Versions

* Node.js: 
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by wennmo** [comment]
Hi @LiKang6688, not sure what ts definitions that are being consumed here, but shouldn't it be
`const app = session.open().then(global => global.openDoc(appId));`?

**Comment by LiKang6688** [comment]
Hi @wennmo, yes, my wrong spelling. It should be `openDoc`.
So the type for `global`  is `IGeneratedAPI` and the Property `openDoc` is missing in `IGeneratedAPI`.

**Comment by LiKang6688** [comment]
@types/enigma.js https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/enigma.js is maintained by Konrad Mattheis outside of Qlik. So I close the issue.

**Comment by T-Wizard** [comment]
to solve this use case (not tested)
I think you can add a dependency to `@types/qlik-engineapi` (in addition to `@types/enigma.js`)
and use `session.open<EngineAPI.IGlobal>().then((global) => ...);`
to get a useable type
